import React,{useEffect,useMemo,useRef,useState,useId} from 'react';
import {apiBase,postCalculation} from '../data/source.js';
import {productionCase,commonPriceChange} from '../model/production.js';
import {display,fmt,sourceSheet,sheetLink,isNumber,confirmedFinance,isHistorical,googleLink,executionLabel,initiativeTitle} from '../model/portfolio.js';
import {ViewTitle} from './Common.jsx';
import {CalculationFlow,EffectBridge} from './EffectVisuals.jsx';
import AnnualActualCase,{annualPriceEstimate,annualResultText} from './AnnualActualCase.jsx';
import {normalizeCalculationInput} from '../data/calculation-adapter.js';
import FactorTree from './FactorTree.jsx';
import MechanismCalculator,{MechanismResult,mechanismResultText,mechanismUnits} from './MechanismCalculator.jsx';
import {applyProductionOpex,deferProductionOpex} from '../model/calculator-session.js';
const levers=[['eggs_pct','Закладка яиц','%'],['hatch_pp','Выводимость','п.п.'],['chick_reject_pp','Отбраковка цыплят','п.п.'],['mortality_pp','Падёж','п.п.'],['average_weight_pct','Средний вес','%'],['fcr_pct','Конверсия корма','%'],['slaughter_yield_pp','Выход мяса','п.п.']];
const money=v=>fmt(v==null?null:v/1e6,2,'Ожидает расчёт');
export function productionMetricHints(b){
 const pp=v=>fmt(v*100,2),reduce=(v,change)=>pp(Math.max(0,v-change/100)),hatchStep=Math.min(1,(1-b.hatch_rate)*100),rejectStep=Math.min(.2,b.chick_reject_rate*100),mortalityStep=Math.min(1,b.mortality_rate*100),yieldStep=Math.min(1,(1-b.slaughter_yield)*100);
 return {
  eggs_pct:'Яйца, отправленные в инкубацию за период. +1% добавляет около '+fmt(b.eggs_set*.01,0)+' яиц',
  hatch_pp:'Цыплята, выведенные из 100 заложенных яиц. +'+fmt(hatchStep)+' п.п. повышает выводимость до '+pp(b.hatch_rate+hatchStep/100)+'%',
  chick_reject_pp:'Выведенные цыплята, исключённые из посадки. −'+fmt(rejectStep)+' п.п. снижает долю до '+reduce(b.chick_reject_rate,rejectStep)+'%',
  mortality_pp:'Доля посаженной птицы, погибшей при выращивании. −'+fmt(mortalityStep)+' п.п. снижает её до '+reduce(b.mortality_rate,mortalityStep)+'%',
  average_weight_pct:'Средняя живая масса птицы перед убоем. +1% добавляет около '+fmt(b.live_kg/b.live_heads*.01*1000,0)+' г на птицу',
  fcr_pct:'Корм на 1 кг живого веса. −1% снижает расход до '+fmt(b.fcr*.99,3)+' кг; меньше корма на тот же вес',
  slaughter_yield_pp:'Продукция после убоя из 100 кг живой птицы. +'+fmt(yieldStep)+' п.п. повышает выход до '+pp(b.slaughter_yield+yieldStep/100)+' кг'
 };
}
function Numeric({label,value,onChange,unit,step=.1,readOnly=false,help=null,control=null}){const helpId=useId();return <label className="calculator-number"><span>{label}</span><div><input type="number" aria-label={label} aria-describedby={help?helpId:undefined} data-calculator-control={control||undefined} readOnly={readOnly} step={step} value={value??''} onChange={e=>onChange(e.target.value===''?null:Number(e.target.value))}/><small>{unit}</small></div>{help&&<small id={helpId} className="metric-help">{help}</small>}</label>;}
function productionMetricValue(key,b){return key==='eggs_pct'?b.eggs_set:key==='average_weight_pct'?b.live_kg/b.live_heads:key==='fcr_pct'?b.fcr:b[{hatch_pp:'hatch_rate',chick_reject_pp:'chick_reject_rate',mortality_pp:'mortality_rate',slaughter_yield_pp:'slaughter_yield'}[key]]*100;}
function productionMetricUnit(key){return key==='eggs_pct'?'шт':key==='average_weight_pct'?'кг':key==='fcr_pct'?'кг / кг':'%';}
function productionMetricShown(key,value){const unit=productionMetricUnit(key);return fmt(value,key==='eggs_pct'?0:['average_weight_pct','fcr_pct'].includes(key)?3:2)+(unit==='%'?'':' ')+unit;}
export function ProductionFields({input,onChange}){const id=useId(),b=input.baseline,hints=productionMetricHints(b);return <div className="production-metric-table" role="table" aria-label="Изменения показателей производства"><div className="production-metric-head" role="row"><span role="columnheader">Показатель</span><span role="columnheader">База</span><span role="columnheader">Изменение</span><span role="columnheader">Цель</span></div>{levers.map(([key,label,unit])=>{const baseline=productionMetricValue(key,b),change=input.changes?.[key]??0,target=unit==='п.п.'?baseline+change:baseline*(1+change/100);return <div className="production-metric-row" role="row" key={key}><div role="cell"><label htmlFor={id+'-'+key}>{label}</label><small id={id+'-'+key+'-help'}>{hints[key]}</small></div><span role="cell" className="production-metric-base"><small aria-hidden="true">База</small>{productionMetricShown(key,baseline)}</span><div role="cell" className="production-metric-change"><input id={id+'-'+key} data-calculator-control={key} aria-label={label} aria-describedby={id+'-'+key+'-help'} type="number" step=".1" value={change} onChange={e=>onChange(key,e.target.value===''?0:Number(e.target.value))}/><span>{unit}</span></div><strong role="cell" className="production-metric-target"><small aria-hidden="true">Цель</small>{productionMetricShown(key,target)}</strong></div>;})}</div>;}
function ResultCard({card,result,changes,period,months,kind='profit',parameters=false,onCopy,copied,copyError,extra=null}){
 const main=kind==='working_capital'?result?.one_off_cash_release:kind==='risk'?result?.expected_risk_reduction:kind==='hours'?result?.hours_released:result?.period_delta_ebitda;
 const label=kind==='working_capital'?'Высвобождение оборотного капитала':kind==='risk'?'Снижение ожидаемого риска':kind==='hours'?'Освобождённое время':'Прирост операционной прибыли';
 const unit=kind==='hours'?'ч':'млн руб';
 const estimate=isNumber(card?.priority_annual_ebitda)?card.priority_annual_ebitda:null;
 return <aside className="calculator-result-card" aria-live="polite"><h2>Результат инициативы</h2><span>{label}</span><strong>{kind==='hours'?fmt(main,0,'Требуется расчёт'):money(main)} <small>{unit}</small></strong><p className="caption">{display(period)}{months?' / '+months+' мес':''}{kind==='working_capital'?' / разовый результат':kind==='risk'?' / ожидаемый риск':''}</p>{kind==='hours'&&isNumber(result?.period_delta_ebitda)&&<p className="calculator-secondary-result">Операционная прибыль: {money(result.period_delta_ebitda)} млн руб</p>}{kind==='profit'&&months!==12&&isNumber(result?.annual_run_rate_delta)&&<p className="caption">Годовой темп: {money(result.annual_run_rate_delta)} млн руб</p>}<h3>{parameters?'Параметры расчёта':'Изменённые параметры'}</h3>{changes.length?<dl>{changes.map(([label,value,unit])=><div key={label}><dt>{label}</dt><dd>{!parameters&&value>0?'+':''}{fmt(value)} {unit}</dd></div>)}</dl>:<p className="caption">Исходные параметры сохранены</p>}{extra}{kind==='profit'&&estimate!==null&&!isHistorical(card)&&<p className="calculator-existing-estimate">Оценка в паспорте: {fmt(estimate)} млн руб / год</p>}<p className="caption">Владелец подтверждает показатели и эффект</p><button disabled={!isNumber(main)} onClick={onCopy}>{copied?'Результат скопирован':'Скопировать для паспорта'}</button>{copyError&&<p role="alert" className="caption">{copyError}</p>}<a href={card?googleLink(card):sourceSheet()} target="_blank" rel="noopener noreferrer">Открыть инициативу в реестре</a></aside>;
}
function ResultConditions({result,annual=false,mechanism=false}){const demand=result?.demand?.length>0&&result.demand.every(r=>r.status==='Подтверждено'),capacity=result?.capacities?.length>0&&result.capacities.every(r=>r.status==='Подтверждено');return <section className="calculator-conditions"><div><h2>Условия результата</h2><p className="caption">Владелец подтверждает исходные данные и возможность реализации</p></div><dl><div><dt>Спрос</dt><dd>{annual?'Объём продаж сохраняется':mechanism?'Проверяет владелец':demand?'Подтверждён':'Требуется подтверждение'}</dd></div><div><dt>Мощности</dt><dd>{annual?'Объём производства сохраняется':mechanism?'Проверяет владелец':capacity?'Подтверждены':'Требуется подтверждение'}</dd></div><div><dt>Расходы</dt><dd>{isNumber(result?.period_delta_ebitda)?'Расчётная оценка':'Требуется состав расходов'}</dd></div></dl><a href={sheetLink(807030034)} target="_blank" rel="noopener noreferrer">Проверить параметры в таблице</a>{result?.demand?.some(r=>r.excess_kg>0)&&<p className="notice">Сценарий превышает спрос: {result.demand.filter(r=>r.excess_kg>0).map(r=>r.name).join(' / ')}</p>}{result?.capacities?.some(r=>r.target_loading>1)&&<p className="notice">Сценарий превышает мощность: {result.capacities.filter(r=>r.target_loading>1).map(r=>r.name).join(' / ')}</p>}</section>;}
export default function Calculator({data,list,selectedCode,onSelect,onPrint}){
 const [caseChoice,setCaseChoice]=useState('operating'),[copied,setCopied]=useState(false),[estimateCode,setEstimateCode]=useState(selectedCode),[sourceInput,setSourceInput]=useState(null),[input,setInput]=useState(null),[personal,setPersonal]=useState(false),[error,setError]=useState(''),[apiResult,setApiResult]=useState(null),[annualScenario,setAnnualScenario]=useState(null),[annualPersonal,setAnnualPersonal]=useState(false),[mechanismPrint,setMechanismPrint]=useState(null),[otherMillion,setOtherMillion]=useState(0),[itMillion,setItMillion]=useState(0),[focusRequest,setFocusRequest]=useState('');
 const inputsRef=useRef(null),annualCase=data.annualActualInput;
 useEffect(()=>{setEstimateCode(selectedCode);},[selectedCode]);
 useEffect(()=>{if(annualCase&&!annualPersonal)setAnnualScenario({...annualCase.scenario});},[annualCase,annualPersonal]);
 useEffect(()=>{const src=data.productionInput||data.production_input;if(src){setSourceInput(src);if(!personal)setInput(structuredClone(src));}},[data.productionInput,data.production_input,personal]);
 useEffect(()=>{if(!apiBase)return;const controller=new AbortController();fetch(apiBase+'/api/calculators/source',{signal:controller.signal,cache:'no-store'}).then(r=>r.ok?r.json():Promise.reject()).then(r=>{const src=r.production_input||r.input||r.source_inputs?.production_input;if(src){setSourceInput(src);setInput(structuredClone(src));}}).catch(()=>{});return()=>controller.abort();},[]);
 const calculationInput=useMemo(()=>normalizeCalculationInput(input),[input]);
 const calculated=useMemo(()=>{if(!input)return {result:null,error:''};try{return {result:productionCase(calculationInput),error:''};}catch(e){return {result:null,error:e.message};}},[calculationInput]);
 useEffect(()=>{setApiResult(null);if(!apiBase||!input||calculated.error)return;const controller=new AbortController();const timer=setTimeout(()=>postCalculation(calculationInput,controller.signal).then(r=>{if(r)setApiResult(r);}).catch(e=>{if(e.name!=='AbortError')setError('Расчёт обновлён / дополнительная проверка ожидается');}),450);return()=>{clearTimeout(timer);controller.abort();};},[calculationInput,calculated.error]);
 const adjusted=useMemo(()=>{const base=apiResult||calculated.result;try{return {result:applyProductionOpex(base,{otherMillion,itMillion}),error:''};}catch(e){const pending=deferProductionOpex(base);return {result:pending,error:e.message};}},[apiResult,calculated.result,otherMillion,itMillion]);
 const result=adjusted.result,priceIndex=commonPriceChange(input),annualResult=annualPriceEstimate(annualCase,annualScenario||{});
 const update=fn=>{setPersonal(true);setInput(prev=>{const next=structuredClone(prev);fn(next);return next;});setError('');};
 const allCards=data.initiatives||list,estimateCard=allCards.find(i=>i.code===estimateCode)||allCards[0];
 const changes=scenarioChanges(input,priceIndex,{otherMillion,itMillion}),annualChanges=[['Средняя чистая цена',annualScenario?.price_change_pct??annualScenario?.price_change_percent??0,'%'],['Дополнительные операционные расходы',(annualScenario?.additional_cash_expenses??0)/1e6,'млн руб']].filter(([,value])=>value!==0);
 const mechanismInput=mechanismPrint?.input,mechanismResult=mechanismPrint?.result,mechanismKind=mechanismInput?.kind||'budget',units=mechanismUnits(mechanismInput||{}),mechanismChanges=mechanismParameters(mechanismInput);
 useEffect(()=>{setCopied(false);},[input,annualScenario,mechanismInput,otherMillion,itMillion]);
 useEffect(()=>{if(!focusRequest)return;requestAnimationFrame(()=>{const field=inputsRef.current?.querySelector('[data-calculator-control="'+focusRequest+'"]')||inputsRef.current?.querySelector('input,select');field?.focus();field?.scrollIntoView({behavior:'smooth',block:'center'});setFocusRequest('');});},[focusRequest,caseChoice]);
 const focusProduction=(key)=>{const controls={liveweight:'average_weight_pct',heads:'mortality_pp',placement:'eggs_pct',meat:'slaughter_yield_pp',feed:'fcr_pct',products:'cut_share',mix:'cut_share',sales:'cut_share',fixed:'other_opex',costs:'other_opex',variable:'other_opex',expenses:'other_opex',ebitda:'other_opex'};if(key==='price'){setCaseChoice('annual');setFocusRequest('annual_price');}else{setFocusRequest(controls[key]||key);}};
 const copyResult=async()=>{let text;if(caseChoice==='annual')text=annualResultText(annualResult,annualScenario||{},estimateCard);else if(caseChoice==='mechanism')text=mechanismResultText(mechanismInput,mechanismResult,mechanismPrint?.title,estimateCard,units.quantityUnit,units.metricUnit);else text=[estimateCard?estimateCard.code+' / '+initiativeTitle(estimateCard):'Личный сценарий','Период: '+display(input?.baseline?.period),'Прирост операционной прибыли за период: '+money(result?.period_delta_ebitda)+' млн руб','Годовой темп: '+money(result?.annual_run_rate_delta)+' млн руб / год','Изменения: '+(changes.length?changes.map(([label,value,unit])=>label+' '+fmt(value)+' '+unit).join('; '):'Исходные параметры'),'Предварительная оценка / требуется согласование владельца'].join('\n');if(!text)return;try{await navigator.clipboard.writeText(text);setCopied(true);setTimeout(()=>setCopied(false),2500);}catch{setError('Скопируйте результат из карточки и внесите его в реестр');}};
 const selectCase=key=>{setCaseChoice(key);setCopied(false);setError('');};
 const activeResult=caseChoice==='annual'?annualResult:caseChoice==='mechanism'?mechanismResult:result,period=caseChoice==='annual'?annualResult.period:caseChoice==='mechanism'?mechanismInput?.period:input?.baseline?.period,months=caseChoice==='annual'?12:caseChoice==='mechanism'?mechanismInput?.months:input?.baseline?.months;
 return <section className="calculator-unified"><ViewTitle title="Показатели инициативы определяют прирост прибыли" description="Выберите инициативу, измените показатели и перенесите результат в паспорт" onPrint={onPrint?()=>onPrint(caseChoice==='mechanism'?mechanismPrint:caseChoice==='annual'?{annual:true,annualCase,annualScenario,resultInitiative:estimateCard}:{input,result,personal,resultInitiative:estimateCard,scenarioChanges:changes}):null}/>
 <label className="calculator-result-initiative calculator-initiative-select">Инициатива<select aria-label="Инициатива для результата" value={estimateCard?.code||''} onChange={e=>{setEstimateCode(e.target.value);onSelect?.(e.target.value);setCopied(false);}}>{allCards.map(i=><option value={i.code} key={i.code}>{i.code} / {initiativeTitle(i)}</option>)}</select></label>
 <div className="calculator-case-tabs" role="group" aria-label="Вид эффекта">{[['operating','Выпуск и структура'],['annual','Средняя цена'],['mechanism','Расходы и ресурсы']].map(([key,label])=><button key={key} aria-pressed={caseChoice===key} onClick={()=>selectCase(key)}>{label}</button>)}</div>
 <div className="calculator-workbench"><section className="calculator-inputs" ref={inputsRef}>
 {caseChoice==='operating'&&(!input?<p className="empty">Производственные параметры загружаются из Google-реестра</p>:<><h2>Измените показатели выпуска</h2><p className="caption calculator-period">{display(input.baseline.period)} / {input.baseline.months} мес</p><p className="caption">% меняют показатель относительно базы / п.п. меняют долю</p><ProductionFields input={input} onChange={(key,value)=>update(x=>{x.changes={...x.changes,[key]:value};})}/><h3>Структура продукции</h3><p className="caption">Требуется база структуры / исходный сравнительный расчёт: тушка 100%</p><div className="calculator-compact-inputs">{input.routes.filter(r=>r.kind!=='whole').map(r=><Numeric key={r.code} control={r.kind==='cut'?'cut_share':'deep_share'} label={r.kind==='cut'?'Целевая доля разделки':'Целевая доля глубокой переработки'} unit="%" value={r.target_share*100} onChange={v=>update(x=>{x.routes.find(row=>row.code===r.code).target_share=(v??0)/100;const whole=x.routes.find(row=>row.kind==='whole');if(whole)whole.target_share=Math.max(0,1-x.routes.filter(row=>row.code!==whole.code).reduce((a,row)=>a+row.target_share,0));})}/>)}<div className="calculator-readonly-share"><span>Тушка / остаток</span><strong>{fmt((input.routes.find(r=>r.kind==='whole')?.target_share??0)*100)}%</strong></div></div><p className="caption">Доли составляют {fmt(input.routes.reduce((sum,r)=>sum+r.target_share,0)*100)}% / владелец подтверждает выходы и вклад переработки</p><h3>Дополнительные расходы за период</h3><div className="calculator-compact-inputs"><Numeric control="other_opex" label="Прочие операционные изменения" unit="млн руб" value={otherMillion} onChange={setOtherMillion} help="Рост расходов: положительное значение / экономия: отрицательное"/><Numeric label="Сопровождение ИТ" unit="млн руб" value={itMillion} onChange={setItMillion} help="Дополнительные расходы сверх учтённых в базе"/></div></>)}
 {caseChoice==='annual'&&<AnnualActualCase actualCase={annualCase} scenario={annualScenario||{}} initiative={estimateCard} embedded compact onScenarioChange={value=>{setAnnualScenario(value);setAnnualPersonal(true);}}/>}
 {caseChoice==='mechanism'&&<MechanismCalculator data={data} onResult={setMechanismPrint} initiative={estimateCard} embedded/>}
 </section><ResultCard parameters={caseChoice==='mechanism'} card={estimateCard} result={activeResult} changes={caseChoice==='annual'?annualChanges:caseChoice==='mechanism'?mechanismChanges:changes} period={period} months={months} kind={caseChoice==='mechanism'&&['hours','working_capital','risk'].includes(mechanismKind)?mechanismKind:'profit'} onCopy={copyResult} copied={copied} copyError={error}/></div>
 <div className="tools calculator-actions"><a className="button-link" href={sheetLink(807030034,caseChoice==='annual'?'B300:J316':undefined)} target="_blank" rel="noopener noreferrer">Исходные параметры</a>{caseChoice==='operating'&&sourceInput&&<button onClick={()=>{setInput(structuredClone(sourceInput));setPersonal(false);setOtherMillion(0);setItMillion(0);setError('');}}>Вернуть исходный сценарий</button>}{caseChoice==='annual'&&<button onClick={()=>{setAnnualPersonal(false);setAnnualScenario({...annualCase?.scenario});setError('');}}>Вернуть исходный сценарий</button>}</div>
 {caseChoice==='operating'&&(calculated.error||adjusted.error)&&<p className="notice" role="alert">{calculated.error||adjusted.error}</p>}
 <ResultConditions result={activeResult} annual={caseChoice==='annual'} mechanism={caseChoice==='mechanism'}/>
 {caseChoice==='operating'&&input&&<><FactorTree input={input} result={result} onEditor={focusProduction}/>{result&&<EffectBridge result={result}/>}</>}
 </section>;
}

export function mechanismParameters(input={}){
 const kind=input?.kind||'budget',units=mechanismUnits(input||{});
 const rows=kind==='budget'?[['Расходы базы',input?.quantity,'руб'],['Снижение расходов',isNumber(input?.target)?100-input.target:null,'%']]:[['База показателя',input?.baseline,units.metricUnit],['Цель показателя',input?.target,units.metricUnit],['Объём',input?.quantity,units.quantityUnit]];
 if(['resource','hours'].includes(kind))rows.push(['Цена ресурса',input?.rate,kind==='hours'?'руб / ч':'руб / ед. ресурса']);
 if(kind==='hours')rows.push(['Доля времени с денежной экономией',isNumber(input?.monetization)?input.monetization*100:null,'%']);
 if(['budget','resource','hours'].includes(kind))rows.push(['Дополнительные расходы',isNumber(input?.additional_opex)?input.additional_opex/1e6:null,'млн руб']);
 return rows.filter(([,value])=>isNumber(value));
}
export function scenarioChanges(input,priceIndex,{otherMillion=0,itMillion=0}={}){
 const changes=[...levers.map(([key,label,unit])=>[label,input?.changes?.[key]||0,unit]),['Цены продукции',priceIndex,'%'],...(input?.routes||[]).map(r=>[r.name,(r.target_share-r.baseline_share)*100,'п.п.']),...(priceIndex===null?(input?.products||[]).filter(p=>p.kind==='sale'&&isNumber(p.target_price)&&isNumber(p.baseline_price)).map(p=>[p.name,p.target_price-p.baseline_price,'руб / кг']):[]),...(input?.costs||[]).filter(c=>isNumber(c.target_rate)&&isNumber(c.baseline_rate)).map(c=>[c.name,c.target_rate-c.baseline_rate,c.unit||'руб / единицу']),['Постоянные расходы',isNumber(input?.target_fixed_expenses)&&isNumber(input?.baseline_fixed_expenses)?(input.target_fixed_expenses-input.baseline_fixed_expenses)/1e6:null,'млн руб']];
 return [...changes,['Прочие операционные изменения',otherMillion,'млн руб'],['Сопровождение ИТ',itMillion,'млн руб']].filter(([,value])=>isNumber(value)&&Math.abs(value)>1e-10);
}
export function InitiativeEstimate({data,card,cards=[],onSelect}){
 if(!card)return <p className="empty">Выберите инициативу</p>;
 const historical=isHistorical(card),lever=(data.levers||[]).find(l=>l.code===card.code),annual=isNumber(card.priority_annual_ebitda)?card.priority_annual_ebitda:lever?.annual_ebitda,approved=confirmedFinance(data,card);
 const hours=isNumber(card.total_hours)?card.total_hours:null,rate=isNumber(card.priority_hour_rate)?card.priority_hour_rate:null,payroll=hours!==null&&rate!==null?hours*rate/1e6:null;
 return <section className="initiative-estimate"><div className="gantt-selector"><label>Инициатива<select aria-label="Инициатива для предварительной оценки" value={card.code} onChange={e=>onSelect?.(e.target.value)}>{cards.map(i=><option key={i.code} value={i.code}>{i.code} / {initiativeTitle(i)}</option>)}</select></label><a className="button-link" href={googleLink(card)} target="_blank" rel="noopener noreferrer">Открыть паспорт в реестре</a></div><h2>{card.code} / {initiativeTitle(card)}</h2><p className="caption">{historical?'История / '+executionLabel(card):approved?'Финансовое согласование подтверждено':'Предварительная оценка / руководитель подтверждает эффект, сроки и стоимость'}</p>{historical?<p className="notice">Карточка сохраняет выполненные работы и фактический статус</p>:<><div className="initiative-estimate-summary"><div><span>Годовой прирост операционной прибыли</span><strong>{fmt(annual)} <small>млн руб / год</small></strong><p>{card.effect_role==='Поддерживающий вклад'?'Расходы поддержки':display(card.effect_group)||'Вклад выбранной инициативы'}</p></div><div><span>До внедрения после запуска</span><strong>{fmt(card.priority_duration_months)} <small>мес</small></strong></div></div><div className="table-wrap"><table><thead><tr><th>Ресурс</th><th>Оценка</th><th>Основание</th></tr></thead><tbody><tr><td>Работа ИТ-команды</td><td>{fmt(hours,0)} ч</td><td>Остаток работ на 2027 год</td></tr><tr><td>Ставка начисленной зарплаты</td><td>{fmt(rate,0)} руб / ч</td><td>Предварительная ставка</td></tr><tr><td>Фонд оплаты труда</td><td>{fmt(payroll)} млн руб</td><td>Часы × ставка / ресурс команды</td></tr><tr><td>Закупки и внешние контракты</td><td>{fmt(card.one_off_2027)} млн руб</td><td>Платежи внедрения 2027</td></tr><tr><td>Сопровождение</td><td>{fmt(card.run_2027)} млн руб</td><td>Расходы 2027</td></tr></tbody></table></div>{card.provenance?.assessment?.requires_capital_scope_confirmation&&<p className="notice">Требуется подтверждение: полный состав оборудования и закупок</p>}<div className="initiative-estimate-basis"><h3>Что меняет инициатива</h3><p>{display(card.problem||card.description)}</p><dl><div><dt>Показатель</dt><dd>{display(card.metric||lever?.metric)||'Требуется показатель'}</dd></div><div><dt>База</dt><dd>{isNumber(card.baseline)?fmt(card.baseline,3):display(card.baseline)||'Требуется база'}</dd></div><div><dt>Цель</dt><dd>{isNumber(card.target)?fmt(card.target,3):display(card.target)||'Требуется цель'}</dd></div></dl></div></>}</section>;
}

export function CalculatorPrint({input,result,personal,educational,annual,annualCase,annualScenario,mechanism,title,initiative,data,resultInitiative,scenarioChanges=[]}){if(initiative)return <InitiativeEstimate data={data} card={initiative}/>;if(mechanism)return <section><h1>{title} / расчёт рычага</h1>{resultInitiative&&<p>{resultInitiative.code} / {initiativeTitle(resultInitiative)}</p>}<p>База {fmt(input?.baseline)} / цель {fmt(input?.target)} {mechanismUnits(input||{}).metricUnit}</p><p>Объём: {fmt(input?.quantity)} {mechanismUnits(input||{}).quantityUnit}{isNumber(input?.rate)?' / тариф: '+fmt(input.rate)+(input.kind==='hours'?' руб / ч':input.kind==='resource'?' руб / ед. ресурса':' руб / единицу'):''}{isNumber(input?.monetization)?' / доля времени с денежной экономией: '+fmt(input.monetization*100)+'%':''}</p><p>Дополнительные расходы: {fmt(input?.additional_opex)} руб</p><p>Период: {input?.period} / {input?.months} месяцев</p>{result?<MechanismResult result={result}/>:<p>Требуются параметры</p>}</section>;if(annual)return <AnnualActualCase actualCase={annualCase} scenario={annualScenario} initiative={resultInitiative}/>;return <section className={educational?"calculator-example":""}><h1>Производственный расчёт связывает объём и операционную прибыль</h1>{resultInitiative&&<p>{resultInitiative.code} / {initiativeTitle(resultInitiative)}</p>}{scenarioChanges.length>0&&<p>Изменения: {scenarioChanges.map(([label,value,unit])=>label+' '+fmt(value)+' '+unit).join(' / ')}</p>}<p>{input?.baseline?.period} / {educational?'Учебный числовой сценарий / личный расчёт на согласовании':personal?'Личный сценарий на согласовании':result?.status}</p><p className="caption">Цены корзины: {display(input?.sources?.prices)||"Период проходит согласование"}</p><CalculationFlow input={input} result={result}/>{result&&<><EffectBridge result={result}/><p>Годовой темп изменения операционной прибыли: {money(result.annual_run_rate_delta)} млн руб</p><p>Согласование: {result.confirmation_fields.join(', ')||'Подтверждено'}</p><table><thead><tr><th>Ограничение</th><th>Поток цели</th><th>Мощность цели</th><th>Загрузка</th><th>Статус</th></tr></thead><tbody>{result.capacities.map(r=><tr key={r.code}><td>{r.name}</td><td>{fmt(r.target_load,0)}</td><td>{fmt(r.target_capacity,0,'Требуется значение')}</td><td>{r.target_loading==null?'Требуется норма':fmt(r.target_loading*100)+'%'}</td><td>{r.status}</td></tr>)}</tbody></table></>}</section>;}
