import React from 'react';
import Icon from './Icon.jsx';
import {annualForecast} from '../model/assessment.js';
import {display,initiativeTitle,processGroup,color,fmt,shortDate,sourceSheet,mergedCount,isNewIdea,isHistorical,isNumber} from '../model/portfolio.js';
export function Legend(){return <div className="legend"><span><i className="source-swatch"/>Исходные инициативы и поля</span><span><i className="addition-swatch"/>Дополнения</span><span><i className="formula-swatch"/>Расчёт</span><span><i className="priority-swatch"/>Приоритет</span></div>;}
export function SourceStatus({source}){const time=v=>v?new Date(v).toLocaleTimeString('ru-RU',{timeZone:'Europe/Moscow',hour:'2-digit',minute:'2-digit'}):'ожидается';const current=time(source.sourceCheckedAt||source.lastChecked);return <section className="live-status" data-state={source.error?'error':source.loading&&!source.data?'loading':source.stale?'stale':'online'} aria-live="polite"><div className="live-status-line"><span className="live-dot"/><div className="live-source"><strong>{source.error||source.stale?`Данные ожидают обновления${source.data?' / срез '+current:''}`:source.data?'Обновлено '+current:'Данные загружаются'}</strong></div></div><div className="source-actions"><a className="button-link primary" href={sourceSheet()} target="_blank" rel="noopener noreferrer"><Icon name="external"/>Редактировать реестр</a><button onClick={source.refresh} className="button-with-icon" disabled={source.loading}><Icon name="refresh"/>Обновить</button></div></section>;}
export function ViewTitle({title,description,onPrint}){return <div className="view-title"><div><h1>{title}</h1>{description&&<p className="caption">{description}</p>}</div>{onPrint&&<div className="tools"><button onClick={onPrint}><Icon name="print"/>Печать / PDF</button></div>}</div>;}
export function Code({i,onOpen}){return <button className={'code-button '+(i.provenance?.origin==='primary'?'source-primary':'addition')} onClick={()=>onOpen(i.code)}>{i.code}</button>;}
export function FieldValue({i,name,empty='Требуется заполнение'}){return <span className={color(i,name)}>{(name==='title'?initiativeTitle(i):name==='process'?processGroup(i):display(i[name]))||empty}</span>;}
export function PrintMeta({data,source}){return <><p className="caption">Срез {shortDate(data.asOf)}{source.stale||source.error?' / данные ожидают обновления':''}</p><Legend/></>;}
export function MetricStrip({cards,finance}){const current=cards.filter(i=>!isNewIdea(i)&&!isHistorical(i)).length,ideas=cards.filter(isNewIdea).length,history=cards.filter(isHistorical).length,estimated=cards.filter(i=>!isHistorical(i)&&isNumber(i.priority_annual_ebitda)),net=annualForecast(cards).value;return <><div className="metric-strip overview-counts">{[['Текущих проектов',current],['Входящих идей',ideas],['Исторических работ',history]].map(([label,count])=><div className="metric" key={label}><label>{label}</label><strong className="number">{count}</strong></div>)}</div><div className="overview-finance"><strong>{net!==null?'Предварительный годовой прирост операционной прибыли: '+fmt(net)+' млн руб':'Оценки прибыли проходят согласование'}</strong><span>Карточек с оценкой: {estimated.length} / согласованных эффектов: {finance.confirmedCount}</span></div></>;}
