import React,{useLayoutEffect,useMemo,useRef,useState} from 'react';
import {productionTreeModel} from '../model/factor-tree.js';
import {display,fmt,isNumber} from '../model/portfolio.js';
import '../factor-tree.css';
const operations=[['ebit','ebitda','−'],['ebit','depreciation',''],['ebitda','revenue','−'],['ebitda','expenses',''],['revenue','sales','×'],['revenue','price',''],['expenses','variable','+'],['expenses','fixed','']];
const moneyLayout={ebit:[475,0],ebitda:[255,182],depreciation:[805,182],revenue:[125,364],expenses:[565,364],sales:[0,546],price:[250,546],variable:[690,546],fixed:[940,546]};
const physicalLayout={sales:[475,0],meat:[255,182],mix:[805,182],liveweight:[125,364],yield:[440,364],heads:[0,546],weight:[310,546],feed:[805,546],placement:[0,728],survival:[310,728],fcr:[940,728],eggs:[0,910],hatch:[250,910],reject:[500,910]};
const physicalEdges=[['sales','meat','× индекс'],['sales','mix','× индекс'],['meat','liveweight','× индекс'],['meat','yield','× индекс'],['liveweight','heads','× индекс'],['liveweight','weight','× индекс'],['heads','placement','× индекс'],['heads','survival','× индекс'],['placement','eggs','× индекс'],['placement','hatch','× индекс'],['placement','reject','× индекс'],['feed','liveweight','× индекс'],['feed','fcr','× индекс']];
const shortFormula={ebit:'Прирост EBITDA − амортизация',ebitda:'Изменение выручки − расходов',revenue:'Продажи × цена',expenses:'Переменные + постоянные',sales:'Сумма конечных продуктов',variable:'Драйверы × ставки',fixed:'Расходы за период',meat:'Живой вес × выход',liveweight:'Головы × средняя масса',heads:'База × индексы посадки и сохранности',placement:'База × индексы закладки и вывода',mix:'Разделка / переработка / тушка',feed:'База × индексы живой массы и конверсии',depreciation:'Амортизация за тот же период'};
function shown(value,node){if(!isNumber(value))return 'Уточнить';return fmt(node.unit==='млн руб'?value/1e6:node.unit==='%'?value*100:value,node.unit==='кг'||node.unit==='гол'||node.unit==='шт'?0:2);}
function Edges({layout,edges,heights}){return <svg className="factor-tree-lines" viewBox={'0 0 1180 '+(Object.hasOwn(layout,'ebit')?1000:1580)} aria-hidden="true"><defs><marker id="factor-arrow" viewBox="0 0 10 10" refX="8" refY="5" markerWidth="5" markerHeight="5" orient="auto-start-reverse"><path d="M0 0 L10 5 L0 10 Z" fill="#6e8ca8"/></marker></defs>{edges.map(([a,b,op],k)=>{const from=layout[a],to=layout[b];if(!from||!to)return null;const sx=from[0]+110,sy=from[1]+(heights[a]||210)+4,tx=to[0]+110,ty=to[1]-4,mid=(sy+ty)/2;const path=a==='feed'&&b==='liveweight'?`M${to[0]+110},${to[1]+(heights[b]||210)+4} V${(to[1]+(heights[b]||210)+from[1])/2} H${from[0]+110} V${from[1]-4}`:`M${tx},${ty} V${mid} H${sx} V${sy}`;return <g key={a+b}><path d={path} markerEnd="url(#factor-arrow)"/>{op&&<g><rect x={tx-(op.length>1?39:13)} y={mid-13} width={op.length>1?78:26} height="26" rx={op.length>1?7:13}/><text x={tx} y={mid+5} style={{fontSize:op.length>1?12:19}}>{op}</text></g>}</g>;})}</svg>;}
export default function FactorTree({input,result,onEditor,customModel=null,title="Факторы связывают производство с приростом прибыли"}){
 const canvas=useRef(null),[heights,setHeights]=useState({});const model=useMemo(()=>customModel||productionTreeModel(input,result),[input,result,customModel]),[mode,setMode]=useState('money'),[selected,setSelected]=useState('');const layout=Object.fromEntries(Object.entries(mode==='money'?moneyLayout:physicalLayout).map(([id,[x,y]])=>[id,[x,Math.round(y*(mode==='physical'?1.43:1.3))]]));
 useLayoutEffect(()=>{let centered=false;const measure=()=>{if(!canvas.current?.offsetHeight)return;const next={};canvas.current.querySelectorAll('[data-factor-node]').forEach(e=>{next[e.dataset.factorNode]=e.offsetHeight;});setHeights(prev=>JSON.stringify(prev)===JSON.stringify(next)?prev:next);const scroller=canvas.current.parentElement;if(!centered&&scroller?.clientWidth){if(scroller.clientWidth<1180)scroller.scrollLeft=Math.max(0,585-scroller.clientWidth/2);centered=true;}};measure();const observer=new ResizeObserver(measure);if(canvas.current)observer.observe(canvas.current);return()=>observer.disconnect();},[mode]);
 const open=node=>{setSelected(node.id);onEditor(node.editor||node.id,node.title);if(node.id==='sales'&&!customModel)setMode('physical');};
 return <section className="factor-tree" aria-label="Интерактивное дерево производственных факторов"><div className="factor-tree-heading"><div><h2>{title}</h2><p>{display(model.period)} / {model.months} месяцев / база, сценарий и изменение</p></div>{!customModel&&<div className="factor-tree-modes"><button aria-pressed={mode==='money'} onClick={()=>setMode('money')}>Денежный результат</button><button aria-pressed={mode==='physical'} onClick={()=>setMode('physical')}>Производственные факторы</button></div>}</div><p className="factor-tree-guidance">Нажмите показатель, чтобы изменить его параметры. Стрелки связывают факторы с результатом</p>{mode==='physical'&&<p className="factor-tree-index-note">Индекс = сценарий / база. Объём сценария = наблюдаемая база × индексы связанных факторов; период сохраняет переходящие стада</p>}<label className="factor-tree-jump">Изменить показатель<select aria-label="Изменить показатель дерева" value="" onChange={e=>{const n=model.byId[e.target.value];if(n)open(n);}}><option value="">Выберите показатель</option>{Object.keys(layout).filter(id=>model.byId[id]).map(id=><option key={id} value={id}>{model.byId[id].title}</option>)}</select></label><div className="factor-tree-scroll"><div ref={canvas} className={'factor-tree-canvas '+mode}><Edges layout={layout} heights={heights} edges={(mode==='money'?operations:physicalEdges).filter(([a,b])=>model.byId[a]&&model.byId[b])}/>{Object.entries(layout).map(([id,[x,y]])=>{const n=model.byId[id];if(!n)return null;return <button className={'factor-node '+(selected===id?'selected ':'')+(n.editor?'editable':'computed')} style={{left:x,top:y}} key={id} data-factor-node={id} data-factor-index={n.index??undefined} onClick={()=>open(n)} aria-label={n.title+' / изменить параметры'}><div className="factor-node-title">{n.image&&<img src={import.meta.env.BASE_URL+'assets/production-ai/'+n.image} alt="Взвешивание бройлера"/>}<strong>{n.title}</strong><small>{n.unit}</small></div><div className="factor-node-values"><span>База<b title={String(n.baseline??'')}>{shown(n.baseline,n)}</b></span><span>Сценарий<b title={String(n.target??'')}>{shown(n.target,n)}</b></span></div><div className="factor-node-delta"><span>Изменение</span><b>{isNumber(n.change)?(n.change>0?'+':'')+shown(n.change,n)+(n.unit==='%'?' п.п.':''):'Ожидает расчёт'}</b></div>{mode==='physical'&&isNumber(n.index)&&<small className="factor-node-index">Индекс × {fmt(n.index,5)}</small>}<small className="factor-node-formula" title={n.formula}>{mode==='physical'&&['heads','placement','feed'].includes(id)?n.formula:shortFormula[id]||n.formula||'Вход производственного сценария'}</small></button>;})}</div></div><p className="factor-tree-footnote">EBIT – прибыль до процентов и налога; EBITDA – прибыль до процентов, налога и амортизации. {customModel?'Сценарий сохраняет состав и период тех же продаж':'Коэффициенты периода сохраняют наблюдаемую базу производства'}</p></section>;
}
