import React,{useLayoutEffect,useMemo,useRef,useState} from 'react';
import {productionTreeModel} from '../model/factor-tree.js';
import {display,fmt,isNumber} from '../model/portfolio.js';
import '../factor-tree.css';
const operations=[['ebitda','revenue','−'],['ebitda','expenses',''],['revenue','sales','×'],['revenue','price',''],['expenses','variable','+'],['expenses','fixed','']];
const physicalEdges=[['sales','meat','× индекс'],['sales','mix','× индекс'],['meat','liveweight','× индекс'],['liveweight','heads','× индекс'],['heads','placement','× индекс'],['feed','liveweight','× индекс']];
const physicalLevels=[['placement','heads','liveweight','feed'],['meat','mix'],['sales','price','variable','fixed'],['revenue','expenses'],['ebitda']];
const moneyLevels=[['sales','price'],['revenue','expenses'],['ebitda']];
const shortFormula={ebitda:'Изменение выручки − расходов',revenue:'Продажи × цена',expenses:'Переменные + постоянные',sales:'Сумма конечных продуктов',variable:'Объём × ставка',fixed:'Расходы за период',meat:'Живой вес × выход',liveweight:'Головы × средняя масса',heads:'База × индексы посадки и сохранности',placement:'База × индексы закладки и вывода',mix:'Разделка / переработка / тушка',feed:'База × индексы живой массы и конверсии'};
function shown(value,node){if(!isNumber(value))return 'Уточнить';return fmt(node.unit==='млн руб'?value/1e6:node.unit==='%'?value*100:value,node.unit==='кг'||node.unit==='гол'||node.unit==='шт'?0:2);}
function Edges({layout,edges,width,height}){return <svg className="factor-tree-lines" viewBox={`0 0 ${width} ${height}`} aria-hidden="true">{edges.map(([parent,child,op])=>{const to=layout[parent],from=layout[child];if(!from||!to)return null;const sameLevel=Math.abs(from.y-to.y)<10,sx=sameLevel?from.x+from.width:from.x+from.width/2,sy=sameLevel?from.y+from.height/2:from.y+from.height,tx=sameLevel?to.x:to.x+to.width/2,ty=sameLevel?to.y+to.height/2:to.y,mid=(sy+ty)/2;return <g key={parent+child}><path d={sameLevel?`M${sx},${sy} H${tx}`:`M${sx},${sy} V${mid} H${tx} V${ty}`}/>{op&&!sameLevel&&<g><rect x={tx-(op.length>1?39:13)} y={mid-13} width={op.length>1?78:26} height="26" rx="8"/><text x={tx} y={mid+5} style={{fontSize:op.length>1?12:19}}>{op}</text></g>}</g>;})}</svg>;}
export default function FactorTree({input,result,onEditor,customModel=null,title="Факторы связывают производство с приростом прибыли"}){
 const canvas=useRef(null),[geometry,setGeometry]=useState({nodes:{},width:1,height:1}),[selected,setSelected]=useState('');
 const model=useMemo(()=>customModel||productionTreeModel(input,result),[input,result,customModel]),levels=(customModel?moneyLevels:physicalLevels).map(row=>row.filter(id=>model.byId[id])).filter(row=>row.length);
 useLayoutEffect(()=>{const measure=()=>{if(!canvas.current?.offsetHeight)return;const frame=canvas.current.getBoundingClientRect(),nodes={};canvas.current.querySelectorAll('[data-factor-node]').forEach(e=>{const r=e.getBoundingClientRect();nodes[e.dataset.factorNode]={x:r.left-frame.left,y:r.top-frame.top,width:r.width,height:r.height};});const next={nodes,width:frame.width,height:frame.height};setGeometry(prev=>JSON.stringify(prev)===JSON.stringify(next)?prev:next);};measure();const observer=new ResizeObserver(measure);if(canvas.current)observer.observe(canvas.current);return()=>observer.disconnect();},[model]);
 const open=node=>{setSelected(node.id);onEditor?.(node.editor||({revenue:'price',ebitda:'costs'})[node.id]||node.id,node.title);};
 return <section className="factor-tree" aria-label="Дерево от производства к операционной прибыли"><div className="factor-tree-heading"><div><h2>{title}</h2><p>{display(model.period)} / {model.months} месяцев / база, сценарий и изменение</p></div></div><p className="factor-tree-guidance">Показатели производства формируют продажи, расходы и операционную прибыль. Нажмите показатель для изменения</p><div ref={canvas} className="factor-tree-tiers"><Edges layout={geometry.nodes} width={geometry.width} height={geometry.height} edges={[...operations,...(!customModel?physicalEdges:[])]}/>{levels.map((row,k)=><div className={'factor-tree-level '+(k===levels.length-1?'result':'')} key={k}>{row.map(id=>{const n=model.byId[id];return <button className={'factor-node '+(selected===id?'selected ':'')+(n.editor?'editable':'computed')} key={id} data-factor-node={id} data-factor-index={n.index??undefined} onClick={()=>open(n)} aria-label={n.title+' / изменить параметры'}><div className="factor-node-title"><strong>{n.title}</strong><small>{n.unit}</small></div><div className="factor-node-values"><span>База<b title={String(n.baseline??'')}>{shown(n.baseline,n)}</b></span><span>Сценарий<b title={String(n.target??'')}>{shown(n.target,n)}</b></span></div><div className="factor-node-delta"><span>Изменение</span><b>{isNumber(n.change)?(n.change>0?'+':'')+shown(n.change,n)+(n.unit==='%'?' п.п.':''):'Ожидает расчёт'}</b></div><small className="factor-node-formula" title={n.formula}>{shortFormula[id]||n.formula||'Вход производственного сценария'}</small></button>;})}</div>)}</div></section>;
}
