import React,{useEffect,useMemo,useState} from 'react';
import {display,fmt,isNumber} from '../model/portfolio.js';
import {mechanismCase} from '../model/mechanisms.js';
const kinds={resource:'Экономия ресурса',yield:'Прирост годного выпуска',quality:'Изменение сортности и вклада',budget:'Снижение покупаемых расходов',working_capital:'Высвобождение оборотного капитала',hours:'Освобождение времени',risk:'Снижение ожидаемого риска'};
const recipeKind=name=>/Кормление|Упаковка|Энергия|Охлаждение/.test(name)?'resource':/Склад/.test(name)?'working_capital':/Администрирование|Простои/.test(name)?'hours':/Ремонт|Логистика/.test(name)?'budget':/Сортировка|Разделка/.test(name)?'quality':'yield';
function defaults(kind){return {kind,quantity:null,baseline:null,target:null,rate:null,additional_opex:null,additional_depreciation:null,months:12,period:'2027',monetization:null};}
function Numeric({label,unit,value,onChange}){return <label className="calculator-number"><span>{label}</span><div><input aria-label={label} type="number" step="any" value={value??''} onChange={e=>onChange(e.target.value===''?null:Number(e.target.value))}/><small>{unit}</small></div></label>;}
export default function MechanismCalculator({data,onResult}){
 const catalogue=(data.modelTables?.mechanisms?.values||[]).filter(row=>row[0]),[recipe,setRecipe]=useState(0),[input,setInput]=useState(()=>defaults('yield'));
 const selected=catalogue[recipe]||['Рычаг инициативы','Показатель','Объём','Удельный вклад'];
 const choose=index=>{setRecipe(index);setInput({...defaults(recipeKind(catalogue[index]?.[0]||'')),...(/Простои/.test(catalogue[index]?.[0]||'')?{metricUnit:'hours'}:{})});};
 const update=(key,value)=>setInput(old=>({...old,[key]:value}));
 const calculated=useMemo(()=>{if(['quantity','baseline','target'].some(key=>!isNumber(input[key])))return {result:null,error:''};try{return {result:mechanismCase(input),error:''};}catch(e){return {result:null,error:e.message};}},[input]);
 useEffect(()=>{onResult?.({mechanism:true,input,result:calculated.result,title:display(selected[0])});},[input,calculated.result,selected[0],onResult]);
 const metricUnit=['yield','quality','budget','risk'].includes(input.kind)?'%':input.kind==='hours'?input.metricUnit==='hours'?'ч / человека за период':'мин / операцию':input.kind==='working_capital'?'дней':'ресурс / единицу';
 const quantityLabel=input.kind==='budget'?'Покупаемые расходы за период':input.kind==='working_capital'?'Стоимость потока за день':input.kind==='risk'?'Размер возможного ущерба':input.kind==='hours'&&input.metricUnit==='hours'?'Число работников':'Объём операций или выпуска';
 const quantityUnit=['budget','working_capital','risk'].includes(input.kind)?'руб':input.kind==='hours'&&input.metricUnit==='hours'?'чел':/Инкубация|Упаковка/.test(selected[0])?'шт':/Выращивание|Отлов/.test(selected[0])?'гол':input.kind==='hours'?'операций':'кг';
 return <section className="mechanism-calculator"><div className="gantt-selector"><label>Участок и рычаг<select aria-label="Участок и рычаг" value={recipe} onChange={e=>choose(Number(e.target.value))}>{catalogue.map((r,k)=><option key={k} value={k}>{display(r[0])} / {display(r[1])}</option>)}</select></label><label>Способ расчёта<select aria-label="Способ расчёта" value={input.kind} onChange={e=>setInput({...defaults(e.target.value),...(e.target.value==='hours'&&/Простои/.test(selected[0])?{metricUnit:'hours'}:{})})}>{Object.entries(kinds).map(([key,title])=><option key={key} value={key}>{title}</option>)}</select></label></div><p className="caption">{display(selected[2])} → {display(selected[1])} → {display(selected[3])}</p><div className="mechanism-layout"><div><h2>Параметры одного рычага</h2><Numeric label={quantityLabel} unit={quantityUnit} value={input.quantity} onChange={v=>update('quantity',v)}/><Numeric label="База показателя" unit={metricUnit} value={input.baseline} onChange={v=>update('baseline',v)}/><Numeric label="Цель показателя" unit={metricUnit} value={input.target} onChange={v=>update('target',v)}/>{['resource','yield','quality','hours'].includes(input.kind)&&<Numeric label={input.kind==='hours'?'Избегаемая стоимость часа':'Вклад единицы / тариф ресурса'} unit={input.kind==='hours'?'руб / ч':input.kind==='resource'?'руб / единицу ресурса':'руб / '+quantityUnit} value={input.rate} onChange={v=>update('rate',v)}/>} {input.kind==='hours'&&<Numeric label="Доля монетизации времени" unit="доля от 0 до 1" value={input.monetization} onChange={v=>update('monetization',v)}/>}<details className="form-section"><summary>Период и дополнительные расходы</summary><Numeric label="Число месяцев периода" unit="мес" value={input.months} onChange={v=>update('months',v)}/><Numeric label="Дополнительные операционные расходы" unit="руб / период" value={input.additional_opex} onChange={v=>update('additional_opex',v)}/><Numeric label="Дополнительная амортизация" unit="руб / период" value={input.additional_depreciation} onChange={v=>update('additional_depreciation',v)}/></details></div><div aria-live="polite"><h2>Результат рычага</h2>{calculated.error&&<p role="alert" className="notice">{display(calculated.error)}</p>}{calculated.result?<MechanismResult result={calculated.result}/>:<p className="empty">Введите объём, базу и цель показателя</p>}<p className="caption">Удельный вклад отражает прирост выручки после дополнительных переменных расходов. Освобождённые часы, оборотный капитал и ожидаемый риск сохраняют отдельные результаты</p><p className="caption">Личный расчёт передаётся владельцу для проверки базы, периода, спроса и мощности</p></div></div></section>;
}
export function MechanismResult({result}){const rows=[['Физическое изменение',result.physical_change,'ед.'],['Освобождённое время',result.hours_released,'ч'],['Валовой денежный вклад',result.period_gross_benefit,'руб'],['Изменение EBITDA за период',result.period_delta_ebitda,'руб'],['Изменение EBIT за период',result.period_delta_ebit,'руб'],['Годовой темп EBITDA',result.annual_delta_ebitda,'руб / год'],['Разовое высвобождение капитала',result.one_off_cash_release,'руб'],['Изменение ожидаемого риска',result.expected_risk_reduction,'руб']].filter(([,v])=>v!==null);return <><dl className="mechanism-results">{rows.map(([label,v,unit])=><div key={label}><dt>{label}</dt><dd>{fmt(v,2)} <small>{unit}</small></dd></div>)}</dl>{result.requirements.length>0&&<p>Требуются параметры: {result.requirements.map(display).join(' / ')}</p>}<p className="caption">Финансовое согласование: требуется подтверждение</p></>;}
