import React,{useEffect,useMemo,useState} from 'react';
import {display,fmt,isNumber,initiativeTitle} from '../model/portfolio.js';
import {mechanismCase} from '../model/mechanisms.js';
const kinds={budget:'Снижение расходов',resource:'Экономия ресурса',hours:'Освобождение времени',working_capital:'Высвобождение оборотного капитала',risk:'Снижение ожидаемого риска'};
function defaults(kind){return {kind,quantity:null,baseline:kind==='budget'?100:null,target:kind==='budget'?100:null,rate:null,additional_opex:0,months:12,period:'2027',monetization:null};}
export const budgetComplement=value=>isNumber(value)?100-value:null;
export function mechanismUnits(input){const kind=input.kind;return {metricUnit:kind==='hours'?'мин / операцию':kind==='working_capital'?'дней':kind==='resource'?'ед. / ед.':['risk','budget','yield','quality'].includes(kind)?'%':'ед.',quantityUnit:kind==='working_capital'?'руб / день':['budget','risk'].includes(kind)?'руб':kind==='hours'?'операций':'ед. выпуска'};}
function Numeric({label,unit,value,onChange}){return <label className="calculator-number"><span>{label}</span><div><input aria-label={label} type="number" step="any" value={value??''} onChange={e=>onChange(e.target.value===''?null:Number(e.target.value))}/><small>{unit}</small></div></label>;}
export function mechanismResultText(input,result,title,initiative,quantityUnit,metricUnit){
 if(!input||!result||![result.period_delta_ebitda,result.hours_released,result.one_off_cash_release,result.expected_risk_reduction].some(isNumber))return null;
 const rateUnit=input.kind==='hours'?'руб / ч':input.kind==='resource'?'руб / единицу ресурса':'руб / '+quantityUnit;
 const parameters=[['Объём',input.quantity,quantityUnit],['База показателя',input.baseline,metricUnit],['Цель показателя',input.target,metricUnit],['Удельный вклад / тариф',input.rate,rateUnit],['Доля времени с денежной экономией',isNumber(input.monetization)?input.monetization*100:null,'%'],['Дополнительные операционные расходы',input.additional_opex,'руб / период']].filter(([,value])=>isNumber(value));
 return [initiative?initiative.code+' / '+initiativeTitle(initiative):'Личный сценарий','Рычаг: '+display(title),'Период: '+display(result.period)+' / '+fmt(result.months,0)+' мес',...parameters.map(([label,value,unit])=>label+': '+fmt(value)+' '+(unit||'')),...(isNumber(result.period_delta_ebitda)?['Прирост операционной прибыли за период: '+fmt(result.period_delta_ebitda/1e6)+' млн руб']:[]),...(isNumber(result.hours_released)?['Освобождённое время: '+fmt(result.hours_released)+' ч']:[]),...(isNumber(result.one_off_cash_release)?['Разовое высвобождение оборотного капитала: '+fmt(result.one_off_cash_release/1e6)+' млн руб']:[]),...(isNumber(result.expected_risk_reduction)?['Снижение ожидаемого риска: '+fmt(result.expected_risk_reduction/1e6)+' млн руб']:[]),...(isNumber(result.annual_delta_ebitda)?['Годовой темп: '+fmt(result.annual_delta_ebitda/1e6)+' млн руб / год']:[]),'Предварительная оценка / требуется согласование'].join('\n');
}
export default function MechanismCalculator({data,onResult,initiative,embedded=false}){
 const[input,setInput]=useState(()=>defaults('budget')),[copied,setCopied]=useState(false),[copyError,setCopyError]=useState('');
 const title=kinds[input.kind],update=(key,value)=>{setCopied(false);setInput(old=>({...old,[key]:value}));};
 const calculated=useMemo(()=>{if(['quantity','baseline','target'].some(key=>!isNumber(input[key])))return {result:null,error:''};try{return {result:mechanismCase(input),error:''};}catch(e){return {result:null,error:e.message};}},[input]);
 useEffect(()=>{onResult?.({mechanism:true,input,result:calculated.result,title,resultInitiative:initiative});},[input,calculated.result,title,onResult,initiative]);
 const {metricUnit,quantityUnit}=mechanismUnits(input),profitKind=['budget','resource','hours'].includes(input.kind);
 const copy=async()=>{const text=mechanismResultText(input,calculated.result,title,initiative,quantityUnit,metricUnit);if(text===null)return;setCopyError('');try{await navigator.clipboard.writeText(text);setCopied(true);setTimeout(()=>setCopied(false),2500);}catch{setCopied(false);setCopyError('Скопируйте код инициативы, параметры и результат из карточки');}};
 return <section className="mechanism-calculator compact"><h2>Измените расход или ресурс</h2><label className="mechanism-kind">Вид результата<select aria-label="Вид результата" value={input.kind} onChange={e=>{setInput(defaults(e.target.value));setCopied(false);}}>{Object.entries(kinds).map(([key,label])=><option key={key} value={key}>{label}</option>)}</select></label>
 <div className="calculator-compact-inputs mechanism-inputs">
 {input.kind==='budget'?<><Numeric label="Покупаемые расходы за период" unit="руб" value={input.quantity} onChange={v=>update('quantity',v)}/><Numeric label="Снижение расходов" unit="%" value={budgetComplement(input.target)} onChange={v=>update('target',budgetComplement(v))}/></>:<>
 <Numeric label={input.kind==='working_capital'?'Стоимость потока за день':input.kind==='risk'?'Размер возможного ущерба':input.kind==='hours'?'Число операций за период':'Объём выпуска за период'} unit={quantityUnit} value={input.quantity} onChange={v=>update('quantity',v)}/>
 <Numeric label={input.kind==='working_capital'?'Базовый срок оборота':input.kind==='risk'?'Вероятность риска в базе':input.kind==='hours'?'Время операции в базе':'Расход ресурса на единицу в базе'} unit={metricUnit} value={input.baseline} onChange={v=>update('baseline',v)}/>
 <Numeric label={input.kind==='working_capital'?'Целевой срок оборота':input.kind==='risk'?'Целевая вероятность риска':input.kind==='hours'?'Целевое время операции':'Целевой расход ресурса на единицу'} unit={metricUnit} value={input.target} onChange={v=>update('target',v)}/>
 {['resource','hours'].includes(input.kind)&&<Numeric label={input.kind==='hours'?'Избегаемая стоимость часа':'Цена единицы ресурса'} unit={input.kind==='hours'?'руб / ч':'руб / ед. ресурса'} value={input.rate} onChange={v=>update('rate',v)}/>} {input.kind==='hours'&&<Numeric label="Доля времени с денежной экономией" unit="%" value={input.monetization===null?null:input.monetization*100} onChange={v=>update('monetization',v===null?null:v/100)}/>}</>}
 {profitKind&&<Numeric label="Дополнительные операционные расходы" unit="млн руб" value={input.additional_opex===null?null:input.additional_opex/1e6} onChange={v=>update('additional_opex',v===null?null:v*1e6)}/>}
 <label className="calculator-number"><span>Период расчёта</span><div><input aria-label="Период расчёта" type="text" value={input.period} onChange={e=>update('period',e.target.value)}/></div></label><Numeric label="Число месяцев периода" unit="мес" value={input.months} onChange={v=>update('months',v)}/>
 </div>
 {input.kind==='hours'&&<p className="caption">Освобождённые часы показывают дополнительную ёмкость команды. Денежная экономия отражает снимаемые расходы</p>}{input.kind==='working_capital'&&<p className="caption">Результат показывает разовое высвобождение денег из оборота</p>}{input.kind==='risk'&&<p className="caption">Результат показывает изменение ожидаемого ущерба</p>}{input.kind==='resource'&&<p className="caption">Объём, расход и тариф используют одну единицу ресурса / например кг корма на кг живого веса</p>}
 {calculated.error&&<p role="alert" className="notice">{display(calculated.error)}</p>}
 {!embedded&&<div aria-live="polite"><h2>Результат инициативы</h2>{calculated.result?<><MechanismResult result={calculated.result}/><button onClick={copy}>{copied?'Результат скопирован':'Скопировать для паспорта'}</button></>:<p className="empty">Введите базу и цель показателя</p>}{copyError&&<p role="alert">{copyError}</p>}</div>}
 </section>;
}

export function MechanismResult({result}){const rows=[['Физическое изменение',result.physical_change,'ед.'],['Освобождённое время',result.hours_released,'ч'],['Валовой денежный вклад',result.period_gross_benefit,'руб'],['Изменение операционной прибыли за период',result.period_delta_ebitda,'руб'],['Годовой темп операционной прибыли',result.annual_delta_ebitda,'руб / год'],['Разовое высвобождение капитала',result.one_off_cash_release,'руб'],['Изменение ожидаемого риска',result.expected_risk_reduction,'руб']].filter(([,v])=>v!==null);return <><dl className="mechanism-results">{rows.map(([label,v,unit])=><div key={label}><dt>{label}</dt><dd>{fmt(v,2)} <small>{unit}</small></dd></div>)}</dl>{result.requirements.length>0&&<p>Требуются параметры: {result.requirements.map(display).join(' / ')}</p>}<p className="caption">Финансовое согласование: требуется подтверждение</p></>;}
