import React,{useState,useId,useRef,useEffect} from 'react';
import {initiativeTitle,processGroup,display,person,stageCode,isHistorical,executionLabel} from '../model/portfolio.js';
import {useProductionAssets} from '../data/production-assets.js';
import {ViewTitle,Code} from './Common.jsx';
import Icon from './Icon.jsx';
import {productionNodes,productionLinks,parentMeatLink,mainStages,supportFunctions,allPlantNodes,matches,plantCoverage} from '../model/plant.js';
export {matches} from '../model/plant.js';
export const nodes=productionNodes;
const lines=name=>{const words=name.split(' '),out=[''];for(const word of words){const last=out.length-1;if((out[last]+' '+word).trim().length>21&&out[last])out.push(word);else out[last]=(out[last]+' '+word).trim();}return out;};

export function PlantSvg({list,onOpen,onNode}){const illustrations=useProductionAssets();return <svg className="plant-svg" viewBox="0 0 1400 980" role="group" aria-label="Маршруты продукции: 13 участков и 17 связей"><g stroke="#6e8ca8" strokeWidth="2" fill="none">{productionLinks.map(([from,to,d])=><path key={from+'-'+to} d={d}/>)}</g><path d={parentMeatLink} fill="none" stroke="#6e8ca8" strokeDasharray="5 5"/><text x="45" y="317" fill="#52677d" fontSize="13">Мясо родительского стада учитывается отдельным потоком</text>{nodes.map(n=>{const items=matches(n,list);return <g key={n.id} transform={`translate(${n.x} ${n.y})`}><g className="site" tabIndex="0" role="button" aria-label={n.name+' / инициатив: '+items.length} onClick={()=>onNode?.(n.id)} onKeyDown={e=>{if(['Enter',' '].includes(e.key)){e.preventDefault();onNode?.(n.id);}}}>{illustrations[n.id]?<image href={illustrations[n.id]} x="0" y="0" width="180" height="140" preserveAspectRatio="xMidYMid meet"/>:<g><path d="M7 36L62 13L125 37L68 61Z" fill="#edf3f8"/><path d="M7 36V69L68 94V61ZM68 61L125 37V70L68 94Z" fill="#edf3f8"/><path className="roof" d="M7 36L36 8L93 8L125 37L68 61Z" fill="#edf3f8" stroke="#6e8ca8"/><path d="M29 45V58M42 50V65M91 56V69M103 50V62" stroke="#6e8ca8" strokeWidth="4"/></g>}</g><g className="site" onClick={()=>onNode?.(n.id)}><text x="0" y="154" fontSize="15" fontWeight="600" fill="#1a1a1a">{lines(n.name).map((line,k)=><tspan key={k} x="0" dy={k?17:0}>{line}</tspan>)}</text><text x="0" y="207" fontSize="13" fill="#52677d">{'Инициатив: '+items.length}</text></g>{items.slice(0,2).map((i,k)=><g key={i.code} role="button" tabIndex="0" aria-label={i.code} onClick={()=>onOpen(i.code)} onKeyDown={e=>{if(['Enter',' '].includes(e.key)){e.preventDefault();onOpen(i.code);}}}><title>{initiativeTitle(i)}</title><rect rx="8" x={k*65} y="218" width="60" height="22" fill={i.provenance?.origin==='primary'?'#fff':'#edf3f8'} stroke="#6e8ca8"/><text x={k*65+4} y="234" fill="#003c72" fontSize="12">{i.code}</text></g>)}</g>;})}</svg>;}
function PlantTile({node,list,illustrations,onNode,selected}){
 const items=matches(node,list);
 return <button className="plant-tile" onClick={()=>onNode?.(node.id)} aria-pressed={selected===node.id} aria-label={node.name+' / инициатив: '+items.length}>
  <span className="plant-tile-image">{illustrations[node.id]?<img src={illustrations[node.id]} alt="" width="640" height="640" loading="eager" decoding="async"/>:<span className="plant-empty-icon"><Icon name="map"/></span>}</span>
  <span className="plant-tile-name">{node.name}</span>{node.output&&<span className="plant-tile-output">{node.output}</span>}
  <span className="plant-tile-count">Инициатив: <b>{items.length}</b></span>
 </button>;
}
export function ValueChain({list,onNode,selected,compact=false,onRoutes}){
 const illustrations=useProductionAssets();
 return <div className={compact?'value-chain value-chain-compact':'value-chain'}>
  <div className="plant-chain-header"><div><h2>Основные этапы</h2>{!compact&&<p className="caption">Семь основных этапов раскрывают 13 производственных участков</p>}</div><span className="plant-chain-meta"><Icon name="map" size={18}/>7 этапов / 13 участков{onRoutes&&<button className="button-with-icon" onClick={onRoutes}><Icon name="map" size={18}/>Открыть подробную цепочку</button>}</span></div>
  <ol className="production-chain" aria-label="Основные этапы производства">{mainStages.map(n=><li key={n.id}><PlantTile node={n} list={list} illustrations={illustrations} onNode={onNode} selected={selected}/></li>)}</ol>
  <section className="support-functions"><h2>Поддерживающие службы обеспечивают всю цепочку производства</h2>{!compact&&<p className="caption">Выберите службу, чтобы открыть связанные инициативы</p>}<div className="support-tiles" aria-label="Поддерживающие функции">{supportFunctions.map(n=><PlantTile key={n.id} node={n} list={list} illustrations={illustrations} onNode={onNode} selected={selected}/>)}</div></section>
 </div>;
}
export default function PlantMap({list,onOpen,onPrint}){
 const[node,setNode]=useState(null),[routes,setRoutes]=useState(!onPrint),dialog=useRef(null),dialogTitle=useId(),illustrations=useProductionAssets();
 const coverage=plantCoverage(list),selected=node==='general'?{id:'general',name:'Общие системы и управление'}:mainStages.find(n=>n.id===node)||allPlantNodes.find(n=>n.id===node),items=node==='general'?coverage.unassigned:selected?matches(selected,list):[];
 useEffect(()=>{if(node&&dialog.current&&!dialog.current.open)dialog.current.showModal();},[node]);
 const open=code=>{dialog.current?.close();setNode(null);onOpen(code);};
 return <section className="plant-map-view">
  <ViewTitle title="Производственные участки раскрывают связанные инициативы" description={`Карта связывает инициативы с участками: ${coverage.linked} / общие системы и уточняемая привязка: ${coverage.unassigned.length}`} onPrint={onPrint}/>
  {!routes&&<ValueChain list={list} onNode={setNode} selected={node} onRoutes={onPrint?()=>{setRoutes(true);requestAnimationFrame(()=>{const section=document.getElementById('production-routes');section?.scrollIntoView({block:'start'});section?.focus({preventScroll:true});});}:undefined}/>}
  {routes&&<div className="production-detail-selector"><button className="button-with-icon" aria-expanded={routes} aria-controls="production-routes" onClick={()=>setRoutes(v=>!v)}><Icon name="map"/>Вернуться к основным этапам</button></div>}
  {routes&&<section className="production-route" id="production-routes" tabIndex="-1" aria-label="Подробная цепочка производства"><h2>Переделы раскрывают маршруты готовой продукции</h2><p className="caption route-description">Корм поступает стаду и бройлеру; разделка, переработка и субпродукты проходят собственные маршруты до упаковки и отгрузки</p><div className="production-detail-selector">{productionNodes.filter(n=>['kill','chilling','cut','deep','other','pack','stock'].includes(n.id)).map(n=><button key={n.id} aria-pressed={node===n.id} onClick={()=>setNode(n.id)}>{n.name}<span className="pill">{matches(n,list).length}</span></button>)}</div><div className="map-wrap"><PlantSvg list={list} onOpen={open} onNode={setNode}/></div></section>}
  <section className="plant-unassigned"><h2>Общие системы и управление</h2><button className="button-link" onClick={()=>setNode('general')}>Инициативы общих систем / {coverage.unassigned.length}</button></section>
  <dialog ref={dialog} className="plant-dialog" aria-labelledby={dialogTitle} onClose={()=>setNode(null)} onClick={e=>{if(e.target===e.currentTarget){const r=e.currentTarget.getBoundingClientRect();if(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom)e.currentTarget.close();}}}>
   {selected&&<><div className="plant-selection-header"><h2 id={dialogTitle}>{selected.name}</h2><button className="button-with-icon" onClick={()=>dialog.current.close()} aria-label="Закрыть список инициатив"><Icon name="close"/>Закрыть</button></div><div className="plant-selection-body">{illustrations[selected.id]&&<img src={illustrations[selected.id]} alt="" width="180" height="180"/>}<div><p className="caption">Инициативы выбранного состава: {items.length} / код открывает паспорт</p>{supportFunctions.some(n=>n.id===node)&&<p className="caption">Владелец подтверждает связь инициативы со службой</p>}{selected.children&&selected.children.length>1&&<div className="production-detail-selector">{productionNodes.filter(n=>selected.children.includes(n.id)).map(n=><button key={n.id} onClick={()=>setNode(n.id)}>{n.name}</button>)}</div>}{items.length?<ul className="plant-initiative-list">{items.map(i=><li key={i.code}><Code i={i} onOpen={open}/><div><button className="link-button" onClick={()=>open(i.code)}>{initiativeTitle(i)}</button><small className="plant-initiative-owner">{person(i)} / {processGroup(i)}</small></div><span className="pill">{isHistorical(i)?executionLabel(i):stageCode(i)}</span></li>)}</ul>:<p className="empty">Владелец добавляет привязку инициатив этого участка в реестр</p>}</div></div></>}
  </dialog>
 </section>;
}
