import React,{useEffect,useMemo,useRef,useState} from 'react';
import {display,initiativeTitle,fmt,person,googleLink,executionLabel,isHistorical} from '../model/portfolio.js';
import {priorityMetrics,priorityProjection} from '../model/priorities.js';
import {ViewTitle,Code} from './Common.jsx';
import {assessment,assessmentBasis,assessmentInputsChanged} from '../model/assessment.js';
import '../priorities.css';
import LegalObligations from './LegalObligations.jsx';
import {obligations} from '../model/legal.js';

const operatingMetrics=i=>{const p=priorityMetrics(i),missing=p.missing.filter(value=>value!=='Дополнительная амортизация');return {...p,ebit:p.ebitda,missing,complete:p.ebitda!==null&&p.resourceCost!==null&&p.duration!==null&&p.duration>=0&&!p.capitalScopePending&&p.invalid.length===0&&(p.legal!=='required'||p.legalBasis.trim().length>0)};};

export default function Priorities({list,onOpen}){
 const[mode,setMode]=useState('3d'),[yaw,setYaw]=useState(-35),[pitch,setPitch]=useState(20),[selected,setSelected]=useState(''),[law,setLaw]=useState(false),drag=useRef(null),chart=useRef(null);
 const rows=useMemo(()=>list.filter(i=>!isHistorical(i)).map(i=>({i,relatedLaw:obligations(i).length>0,...operatingMetrics(i)})),[list]);
 useEffect(()=>{if(selected&&!rows.some(r=>r.code===selected))setSelected('');},[rows,selected]);
 const points=rows.filter(r=>r.complete),scene=priorityProjection(points,{yaw,pitch,mode}),chosen=rows.find(r=>r.code===selected);
 useEffect(()=>{const focus=()=>{const element=chart.current,point=scene.points.find(p=>p.code===selected);if(element&&point&&element.scrollWidth>element.clientWidth){const scale=element.querySelector('svg').getBoundingClientRect().width/900;element.scrollLeft=Math.max(0,Math.min(element.scrollWidth-element.clientWidth,point.x*scale-element.clientWidth/2));}};focus();window.addEventListener('resize',focus);return()=>window.removeEventListener('resize',focus);},[selected,yaw,pitch,mode]);
 const axes=[{key:'resourceCost',name:'Стоимость ресурсов 2027, млн руб',start:[-1,-1,-1],end:[1,-1,-1]},{key:'ebit',name:'Операционная прибыль, млн руб / год',start:[-1,-1,-1],end:[-1,1,-1]},{key:'duration',name:'Длительность реализации, мес.',start:[-1,-1,-1],end:[-1,-1,1]}];
 const rotate=(dy,dp)=>{setYaw(v=>v+dy);setPitch(v=>Math.max(-65,Math.min(65,v+dp)));};
 const pointerDown=e=>{if(e.pointerType==='touch'||mode==='2d'||e.target.closest('[data-priority-point]'))return;drag.current={x:e.clientX,y:e.clientY,yaw,pitch};e.currentTarget.setPointerCapture(e.pointerId);};
 const pointerMove=e=>{if(!drag.current)return;setYaw(drag.current.yaw+(e.clientX-drag.current.x)*.35);setPitch(Math.max(-65,Math.min(65,drag.current.pitch+(e.clientY-drag.current.y)*.25)));};
 return <section className="priorities-view"><ViewTitle title="Приоритеты сравнивают эффект, стоимость ресурсов и срок" description="Больший эффект, меньшие затраты и короткий срок повышают приоритет"/>
  <div className="priority-controls"><div><button aria-pressed={mode==='3d'} className={mode==='3d'?'active':''} onClick={()=>setMode('3d')}>Объёмная диаграмма</button><button aria-pressed={mode==='2d'} className={mode==='2d'?'active':''} onClick={()=>setMode('2d')}>Плоская диаграмма</button></div><div><button onClick={()=>rotate(-15,0)} disabled={mode==='2d'}>Повернуть влево</button><button onClick={()=>rotate(15,0)} disabled={mode==='2d'}>Повернуть вправо</button><button onClick={()=>rotate(0,12)} disabled={mode==='2d'}>Поднять</button><button onClick={()=>rotate(0,-12)} disabled={mode==='2d'}>Опустить</button><button onClick={()=>{setYaw(-35);setPitch(20);}}>Исходный вид</button></div><label><input type="checkbox" checked={law} onChange={e=>setLaw(e.target.checked)}/>Выделить связанные требования</label></div>
  <label className="priority-picker">Инициатива<select aria-label="Инициатива на диаграмме приоритетов" value={selected} onChange={e=>setSelected(e.target.value)}><option value="">Выберите карточку</option>{rows.map(r=><option key={r.code} value={r.code}>{r.code} / {initiativeTitle(r.i)}</option>)}</select></label><div ref={chart} className="priority-chart"><svg viewBox="0 0 900 565" tabIndex="0" role="group" aria-label="Сравнение инициатив по операционной прибыли, стоимости ресурсов и сроку" onPointerDown={pointerDown} onPointerMove={pointerMove} onPointerUp={()=>{drag.current=null;}} onPointerCancel={()=>{drag.current=null;}} onKeyDown={e=>{const move={ArrowLeft:[-15,0],ArrowRight:[15,0],ArrowUp:[0,12],ArrowDown:[0,-12]}[e.key];if(move&&mode==='3d'){e.preventDefault();rotate(...move);}}}>
   {mode==='3d'&&[-1,0,1].flatMap(v=>[{a:[-1,-1,v],b:[1,-1,v]},{a:[v,-1,-1],b:[v,-1,1]}]).map((line,k)=>{const a=scene.project(...line.a),b=scene.project(...line.b);return <line key={k} x1={a.x} y1={a.y} x2={b.x} y2={b.y} className="priority-grid"/>;})}
   {axes.filter(a=>mode==='3d'||a.key!=='duration').map(a=>{const start=scene.project(...a.start),end=scene.project(...a.end);return <g key={a.key}><line x1={start.x} y1={start.y} x2={end.x} y2={end.y} className="priority-axis"/><circle cx={end.x} cy={end.y} r="3" fill="#003c72"/><text x={Math.max(14,Math.min(560,end.x+10))} y={Math.max(22,Math.min(548,end.y-9))} className="priority-axis-label">{a.name}</text>{points.length>0&&<text x={end.x+6} y={Math.min(550,end.y+19)} className="priority-tick">{fmt(scene.ranges[a.key].max,2)}</text>}</g>;})}
   {scene.points.map(p=><g key={p.code} data-priority-point={p.code} role="button" tabIndex="0" aria-label={`${p.code}: прибыль ${fmt(p.ebit)}, стоимость ${fmt(p.resourceCost)}, срок ${fmt(p.duration)}; расчётная оценка`} onClick={()=>setSelected(p.code)} onKeyDown={e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();setSelected(p.code);}}} className={(law&&!p.relatedLaw&&p.legal!=='required'?'priority-muted ':'')+(p.historical?'priority-historical ':'')}><title>{p.code+' / '+initiativeTitle(p.i)+' / '+(p.historical?executionLabel(p.i)+' / ':'')+'расчётная оценка'}</title>{p.legal==='required'||p.relatedLaw?<rect x={p.x-8} y={p.y-8} width="16" height="16" rx="4" fill={selected===p.code?'#f2aa00':'#edf3f8'} stroke="#003c72" strokeWidth="2"/>:<circle cx={p.x} cy={p.y} r={mode==='2d'?Math.min(15,6+Math.sqrt(p.duration)):8} fill={selected===p.code?'#f2aa00':'#edf3f8'} stroke={p.historical?'#52677d':'#003c72'} strokeWidth="2"/>}{(selected===p.code||points.length<=20)&&<text x={p.x+13} y={p.y+4} className="priority-code">{p.code}</text>}</g>)}
   {!points.length&&<g className="priority-empty"><text x="260" y="190">Оцените эффект, ресурсы и срок</text><text x="260" y="220">Таблица показывает поля к заполнению</text></g>}
  </svg></div>
  <p className="priority-mobile-hint">Прокручивайте диаграмму по горизонтали; кнопки поворачивают плоскость</p><p className="priority-caption">Оценено {points.length} из {rows.length} текущих карточек / история: {list.filter(isHistorical).length}. Финансы согласуют расчётные оценки в паспорте. Квадраты показывают связанные требования {mode==='3d'?'Перетаскивайте диаграмму мышью или используйте кнопки поворота':'Размер точки показывает срок реализации'}</p>
  {chosen&&<div className="priority-selected"><div><h2>{chosen.code} / {initiativeTitle(chosen.i)}</h2><p>{chosen.historical?executionLabel(chosen.i)+' / ':''}Расчётная оценка</p><p>Операционная прибыль {fmt(chosen.ebit)} млн руб/год / стоимость {fmt(chosen.resourceCost)} млн руб / срок {fmt(chosen.duration)} мес</p>{chosen.missing.length>0&&<p>{chosen.capitalScopePending?chosen.missing.join(' / '):'Требуется оценка: '+chosen.missing.join(' / ')}</p>}{assessment(chosen.i)?.effect_pool?.owner_code&&assessment(chosen.i).effect_pool.owner_code!==chosen.code&&<div className="priority-dependency"><h3>{display(assessment(chosen.i).effect_pool.contribution_label)||'Вклад в группу'}</h3><p>{display(assessment(chosen.i).effect_pool.dependency_role)} / общий потенциал группы: {fmt(assessment(chosen.i).effect_pool.group_potential?.base)} млн руб / год</p><p>{display(assessment(chosen.i).effect_pool.dependency_confirmation)}. Потенциал группы учитывается у конечного владельца</p><button onClick={()=>onOpen(assessment(chosen.i).effect_pool.owner_code)}>Открыть конечный эффект {assessment(chosen.i).effect_pool.owner_code}</button></div>}<LegalObligations list={[chosen.i]} onOpen={onOpen} compact/><p>Команда: {fmt(chosen.grossPayroll)} млн руб / внедрение: {fmt(chosen.equipment)} млн руб / сопровождение: {fmt(chosen.run)} млн руб</p>{chosen.legal==='required'&&<p>Обязательство по закону: {chosen.legalBasis||'Требуется основание и срок'}</p>}{chosen.historical&&<p>Карточка относится к истории. Новые вложения сравниваются по текущим работам и предложениям</p>}</div><button onClick={()=>onOpen(chosen.code)}>Открыть паспорт</button></div>}
  <LegalObligations list={list} onOpen={onOpen}/><section className="priority-estimates"><h2>Оценки текущих проектов и идей / {rows.length}</h2><div className="table-wrap"><table className="priority-table"><thead><tr><th>Код</th><th>Инициатива / ответственный</th><th>Операционная прибыль, млн руб / год</th><th>Ресурсы, млн руб</th><th>Срок, мес</th><th>Обязательство по закону</th><th>Что требуется оценить</th><th>Действие</th></tr></thead><tbody>{rows.map(r=><tr key={r.code}><td><Code i={r.i} onOpen={onOpen}/></td><td>{initiativeTitle(r.i)}<div className="caption">{person(r.i)}{r.historical?' / '+executionLabel(r.i):''}</div></td><td className="numeric formula">{fmt(r.ebit,2,'Требуется оценка')}</td><td className="numeric formula">{fmt(r.resourceCost,2,'Требуется оценка')}</td><td className="numeric addition">{fmt(r.duration,2,'Требуется оценка')}</td><td>{r.legal==='required'?'Да':r.legal==='voluntary'?'Нет':'Требуется проверка'}{r.relatedLaw&&<div className="caption">Связанных требований: {obligations(r.i).length}</div>}</td><td>{r.invalid.length?r.invalid.join(' / '):r.missing.length?r.missing.join(' / '):'–'}</td><td><a href={googleLink(r.i,'priority_annual_ebitda')} target="_blank" rel="noopener noreferrer">Оценить в таблице</a></td></tr>)}</tbody></table></div></section>
 </section>;
}
