import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs';import {productionCase} from './production.js';
const load=name=>JSON.parse(fs.readFileSync(new URL(`../../../backend/data/${name}`,import.meta.url),'utf8'));
const input=load('production_example.json'),expected=load('production_example_result.json');
const close=(a,b)=>assert.ok(Math.abs(a-b)<1e-6*Math.max(1,Math.abs(b)),`${a} / ${b}`);
test('Браузерный расчёт совпадает с Python по физическим и денежным результатам',()=>{const r=productionCase(input);for(const state of ['baseline','target'])for(const key of ['meat_kg','sold_kg','average_price','revenue','variable_expenses','ebitda'])close(r[state][key],expected[state][key]);for(const key of ['period_delta_ebitda','annual_run_rate_delta','bridge_sum'])close(r[key],expected[key]);r.bridge.forEach((row,k)=>close(row.rub,expected.bridge[k].rub));assert.equal(r.approved_delta_ebitda,null);});
test('Пустые переменные расходы блокируют EBITDA и сохраняют объём',()=>{const r=productionCase({...input,costs_complete:false});assert.equal(r.period_delta_ebitda,null);assert.ok(r.target.meat_kg>0);});
test('Один процентный пункт изменяет долю на0,01',()=>{const r=productionCase({...input,changes:{slaughter_yield_pp:1}});close(r.target.slaughter_yield-r.baseline.slaughter_yield,.01);});
test('Материальный баланс и100%маршрутов проходят обязательный контроль',()=>{const bad=structuredClone(input);bad.routes[0].target_share=.8;assert.throws(()=>productionCase(bad),/100%/);const x=structuredClone(input);x.products[0].route_yields.whole=.5;assert.throws(()=>productionCase(x),/баланс/);});
test('Запас текущего периода требует календарь реализации',()=>{const x=structuredClone(input);x.products[0].kind='stock';x.products[0].baseline_price=0;x.products[0].target_price=0;assert.equal(productionCase(x).period_delta_ebitda,null);});
test('Ставка на голову требует единицу своего драйвера',()=>{const x=structuredClone(input);x.costs[0].driver='live_heads';x.costs[0].unit='руб/кг';assert.throws(()=>productionCase(x),/единицу/);});
test('Нативный сценарий Google сохраняет пустые нормы и денежный допуск',()=>{const native=load('production_native_input.json');const r=productionCase(native);close(r.baseline.meat_kg,112550620.19);assert.equal(r.period_delta_ebitda,null);assert.equal(r.approved_delta_ebitda,null);assert.equal(r.baseline.ebitda,null);assert.equal(r.capacities.length,18);assert.ok(r.capacities.some(x=>x.target_load===null));assert.equal(r.status,'На согласовании');});
test('Нулевая доля маршрута сохраняет пустые ставки и физический расчёт',()=>{const native=load('production_native_input.json');const r=productionCase(native);assert.ok(r.baseline.sold_kg>0);assert.equal(r.baseline.route_quantities.deep,0);const inactive=native.costs.filter(c=>c.driver.startsWith('product:')&&r.baseline.product_quantities[c.driver.slice(8)]===0);assert.ok(inactive.length>0);for(const c of inactive)assert.equal(r.baseline.cost_items[c.code],0);});
import {commonPriceChange} from './production.js';
test('Общая ручка цен отражает единый процент живого сценария',()=>{const x=structuredClone(input);for(const p of x.products)if(p.baseline_price!==null)p.target_price=p.baseline_price*1.05;close(commonPriceChange(x),5);x.products.find(p=>p.baseline_price>0).target_price*=1.1;assert.equal(commonPriceChange(x),null);});

const noCosts=()=>{const x=load('production_native_input.json');x.changes={};for(const p of x.products){p.target_price=p.baseline_price;p.target_route_yields=null;}for(const r of x.routes)r.target_share=r.baseline_share;x.incremental_assumptions=Object.fromEntries(['unknown_rates_unchanged','unknown_fixed_expenses_unchanged','unlisted_expenses_unchanged','price_linked_expenses_unchanged'].map(key=>[key,true]));return x;};
test('Неизменный сценарий сохраняет нулевой прирост и пустую абсолютную EBITDA',()=>{const r=productionCase(noCosts());assert.equal(r.period_delta_ebitda,0);assert.equal(r.baseline.ebitda,null);assert.equal(r.target.ebitda,null);assert.equal(r.approved_delta_ebitda,null);});
test('Цена плюс1% даёт оценку прироста при одинаковых неизвестных расходах',()=>{const x=noCosts();for(const p of x.products)if(p.kind==='sale'&&p.baseline_price!=null)p.target_price=p.baseline_price*1.01;const r=productionCase(x);close(r.period_delta_ebitda,r.baseline.revenue*.01);assert.equal(r.baseline.ebitda,null);assert.equal(r.approved_delta_ebitda,null);assert.equal(r.period_delta_ebit,null);});
test('Изменение выхода при неполном составе затрат сохраняет пустой прирост',()=>{const x=noCosts();x.changes={slaughter_yield_pp:1};assert.equal(productionCase(x).period_delta_ebitda,null);});
test('Изменение известной ставки вычисляет разницу расходов',()=>{const x=noCosts();const c=x.costs.find(c=>c.driver==='feed_kg');c.baseline_rate=23;c.target_rate=24;const r=productionCase(x);close(r.period_delta_ebitda,-r.baseline.feed_kg);assert.equal(r.approved_delta_ebitda,null);});
test('Нулевой и отрицательный прирост амортизации влияют только на EBIT',()=>{for(const v of [0,-5,5]){const x=noCosts();x.additional_depreciation=v;const r=productionCase(x);assert.equal(r.period_delta_ebit,v===0?0:-v);assert.equal(r.approved_delta_ebit,null);}});
test('Другой период амортизации сохраняет EBITDA и ожидает EBIT',()=>{const x=noCosts();x.additional_depreciation=0;x.depreciation_period='Январь–декабрь 2026';const r=productionCase(x);assert.equal(r.period_delta_ebitda,0);assert.equal(r.period_delta_ebit,null);assert.equal(r.depreciation_period_comparable,false);});
test('Амортизация требует конечное число и отдельный логический допуск',()=>{for(const v of [true,NaN,Infinity,'0']){const x=noCosts();x.additional_depreciation=v;assert.throws(()=>productionCase(x));}const x=noCosts();x.depreciation_confirmed='true';assert.throws(()=>productionCase(x));});

test('Пропущенные и ложные предпосылки сохраняют неизвестный прирост',()=>{const x=noCosts();delete x.incremental_assumptions;assert.equal(productionCase(x).period_delta_ebitda,null);const y=noCosts();y.incremental_assumptions.unknown_rates_unchanged='true';assert.throws(()=>productionCase(y));});

test('Пустой источник амортизации сохраняет физику и отдельный денежный допуск',()=>{const x=noCosts();x.depreciation_source='';x.depreciation_period='  ';const copy=structuredClone(x);const r=productionCase(x);assert.ok(r.baseline.meat_kg>0);assert.equal(r.period_delta_ebitda,0);assert.equal(r.period_delta_ebit,null);assert.equal(r.approved_delta_ebit,null);assert.deepEqual(x,copy);x.additional_depreciation=0;x.depreciation_confirmed=true;const z=productionCase(x);assert.equal(z.period_delta_ebit,0);assert.equal(z.approved_delta_ebit,null);});
