// Формулы повторяют backend/app/calculations.py и общий набор эталонных сценариев
const tolerance=1e-8;
const finite=(v,name,min=0)=>{if(typeof v!=='number'||!Number.isFinite(v)||v<min)throw new Error(`Поле «${name}» требует числовое значение от ${min}`);return v;};
const fraction=(v,name)=>{finite(v,name);if(v>1)throw new Error(`Поле «${name}» требует долю от 0 до 1`);return v;};
const optional=(v,name)=>v==null?null:finite(v,name);
const diff=(t,b)=>t==null||b==null?null:t-b;
function validate(d){const b=d.baseline;if(!b?.period?.trim()||!b.source?.trim())throw new Error('Производственная база требует период и источник');if(!Number.isInteger(b.months)||b.months<1||b.months>12)throw new Error('Период требует от 1 до 12 месяцев');for(const key of ['eggs_set','placed_chicks','live_heads','live_kg','fcr'])if(finite(b[key],key)<=0)throw new Error('База требует положительные объёмы');for(const key of ['hatch_rate','chick_reject_rate','mortality_rate','slaughter_yield'])fraction(b[key],key);if(b.hatch_rate<=0||b.slaughter_yield<=0||Math.max(b.chick_reject_rate,b.mortality_rate)>=1)throw new Error('База требует положительные выходы и сохранность');if(b.feed_kg!=null)finite(b.feed_kg,'Корм базы');for(const[key,v]of Object.entries(d.changes))finite(v,key,-Infinity);if(d.currency!=='руб'||d.price_basis!=='После исключения НДС и скидок')throw new Error('Расчёт требует рубли и сопоставимую основу цены');
 if(!d.routes.length||!d.products.length)throw new Error('Расчёт требует маршруты и конечные продукты');
 if(!d.incremental_assumptions||typeof d.incremental_assumptions!=='object'||Array.isArray(d.incremental_assumptions)||Object.entries(d.incremental_assumptions).some(([key,value])=>!['unknown_rates_unchanged','unknown_fixed_expenses_unchanged','unlisted_expenses_unchanged','price_linked_expenses_unchanged'].includes(key)||typeof value!=='boolean'))throw new Error('Предпосылки прироста требуют предусмотренные логические значения');
 const flags=[b.confirmed,d.costs_complete,d.expenses_confirmed,d.demand_confirmed,d.capacity_scope_confirmed,d.depreciation_confirmed,...[...d.routes,...d.products,...d.costs,...d.capacities].map(x=>x.confirmed)];if(flags.some(v=>typeof v!=='boolean'))throw new Error('Подтверждение требует логическое значение');
 for(const rows of [d.routes,d.products,d.costs,d.capacities]){const codes=rows.map(x=>x.code);if(codes.some(x=>typeof x!=='string'||!x.trim())||new Set(codes).size!==codes.length)throw new Error('Коды расчёта требуют уникальные заполненные значения');}
 const routeCodes=new Set(d.routes.map(r=>r.code));for(const r of d.routes){if(!['whole','cut','deep'].includes(r.kind))throw new Error('Маршрут требует вид: тушка / разделка / глубокая переработка');fraction(r.baseline_share,'Доля базы');fraction(r.target_share,'Доля цели');finite(r.added_mass_per_kg,'Добавочная масса');optional(r.target_added_mass_per_kg,'Добавочная масса цели');}for(const key of ['baseline_share','target_share'])if(Math.abs(d.routes.reduce((a,r)=>a+r[key],0)-1)>tolerance)throw new Error('Доли маршрутов требуют сумму 100%');
 for(const p of d.products){if(!['sale','loss','stock'].includes(p.kind))throw new Error('Продукт требует вид: продажа / потери / запас');for(const yields of [p.route_yields,p.target_route_yields||{}])for(const[code,value]of Object.entries(yields)){if(!routeCodes.has(code))throw new Error('Выход продукта требует существующий маршрут');finite(value,'Выход продукта');}optional(p.baseline_price,'Цена базы');optional(p.target_price,'Цена цели');optional(p.additional_demand_kg,'Дополнительный спрос');if(p.kind!=='sale'&&[p.baseline_price,p.target_price].some(v=>v!=null&&v!==0))throw new Error('Запас и потери требуют нулевую выручку');}
 for(const target of [false,true])for(const r of d.routes){if((target?r.target_share:r.baseline_share)<=tolerance)continue;const total=d.products.reduce((a,p)=>a+((target&&p.target_route_yields?p.target_route_yields:p.route_yields)[r.code]||0),0),added=target&&r.target_added_mass_per_kg!=null?r.target_added_mass_per_kg:r.added_mass_per_kg;if(Math.abs(total-(1+added))>tolerance)throw new Error('Матрица конечных выходов требует полный материальный баланс');}
 const drivers=new Set(['feed_kg','placed_chicks','live_heads','live_kg','meat_kg','sold_kg',...d.routes.map(r=>'route:'+r.code),...d.products.map(p=>'product:'+p.code)]);
 for(const c of d.costs){if(!drivers.has(c.driver))throw new Error('Расходы требуют физический драйвер');optional(c.baseline_rate,'Ставка базы');optional(c.target_rate,'Ставка цели');const expected=['placed_chicks','live_heads'].includes(c.driver)?'руб/гол':'руб/кг';if(c.unit&&c.unit!==expected)throw new Error('Ставка требует единицу своего драйвера');}
 for(const c of d.capacities){if(!['кг','гол','упак'].includes(c.unit))throw new Error('Мощность требует физическую единицу');optional(c.capacity_per_month,'Мощность');optional(c.baseline_flow_per_meat_kg,'Поток базы');optional(c.target_flow_per_meat_kg,'Поток цели');optional(c.target_capacity_per_month,'Мощность цели');if(!['monthly_flow','peak_stock'].includes(c.capacity_basis))throw new Error('Мощность требует поток или пиковый запас');optional(c.baseline_peak_stock,'Пиковый запас базы');optional(c.target_peak_stock,'Пиковый запас цели');}optional(d.baseline_fixed_expenses,'Постоянные расходы базы');optional(d.target_fixed_expenses,'Постоянные расходы цели');if(d.additional_depreciation!=null)finite(d.additional_depreciation,'Дополнительная амортизация',-Infinity);for(const[key,label]of [['depreciation_source','Источник амортизации'],['depreciation_period','Период амортизации']])if(d[key]!=null&&(typeof d[key]!=='string'||!d[key].trim()))throw new Error(`Поле «${label}» требует заполненный текст`);}
function productionState(b,c){const hatch=fraction(b.hatch_rate+c.hatch_pp/100,'Выводимость цели'),reject=fraction(b.chick_reject_rate+c.chick_reject_pp/100,'Отбраковка цели'),mortality=fraction(b.mortality_rate+c.mortality_pp/100,'Падёж цели'),yield_=fraction(b.slaughter_yield+c.slaughter_yield_pp/100,'Выход мяса цели');const egg=1+c.eggs_pct/100,weight=1+c.average_weight_pct/100,fcr=1+c.fcr_pct/100;if(Math.min(egg,weight,fcr,hatch,yield_)<=0)throw new Error('Цель требует положительные объёмы и выходы');const placement=egg*hatch/b.hatch_rate*(1-reject)/(1-b.chick_reject_rate),heads=b.live_heads*placement*(1-mortality)/(1-b.mortality_rate),kg=heads*b.live_kg/b.live_heads*weight;return {eggs_set:b.eggs_set*egg,hatch_rate:hatch,chick_reject_rate:reject,placed_chicks:b.placed_chicks*placement,mortality_rate:mortality,live_heads:heads,average_weight_kg:b.live_kg/b.live_heads*weight,live_kg:kg,fcr:b.fcr*fcr,feed_kg:(b.feed_kg??b.live_kg*b.fcr)*kg/b.live_kg*fcr,slaughter_yield:yield_,meat_kg:kg*yield_};}
function basket(d,state,target){const route_quantities=Object.fromEntries(d.routes.map(r=>[r.code,state.meat_kg*(target?r.target_share:r.baseline_share)])),product_quantities={};const revenues=[];for(const p of d.products){const yields=target?(p.target_route_yields||p.route_yields):p.route_yields;const quantity=Object.entries(route_quantities).reduce((a,[code,value])=>a+value*(yields[code]||0),0);product_quantities[p.code]=quantity;const price=target&&p.target_price!=null?p.target_price:p.baseline_price;revenues.push(p.kind!=='sale'||quantity===0?0:price==null?null:quantity*price);}
 const sumKind=kind=>d.products.filter(p=>p.kind===kind).reduce((a,p)=>a+product_quantities[p.code],0),sold_kg=sumKind('sale'),stock_kg=sumKind('stock');const drivers={...state,sold_kg,...Object.fromEntries(Object.entries(route_quantities).map(([k,v])=>['route:'+k,v])),...Object.fromEntries(Object.entries(product_quantities).map(([k,v])=>['product:'+k,v]))};const cost_items=Object.fromEntries(d.costs.map(c=>{const rate=target&&c.target_rate!=null?c.target_rate:c.baseline_rate;return [c.code,Math.abs(drivers[c.driver])<=tolerance?0:rate==null?null:drivers[c.driver]*rate];}));const revenue=revenues.some(v=>v==null)?null:revenues.reduce((a,v)=>a+v,0),variable=!d.costs_complete||Object.values(cost_items).some(v=>v==null)?null:Object.values(cost_items).reduce((a,v)=>a+v,0),fixed=target?d.target_fixed_expenses:d.baseline_fixed_expenses;const share=kind=>d.routes.filter(r=>r.kind===kind).reduce((a,r)=>a+(target?r.target_share:r.baseline_share),0);return {...state,route_quantities,product_quantities,sold_kg,loss_kg:sumKind('loss'),stock_kg,cut_share:share('cut'),deep_share:share('deep'),processing_share:share('cut')+share('deep'),revenue,average_price:revenue==null||sold_kg===0?null:revenue/sold_kg,variable_expenses:variable,fixed_expenses:fixed,ebitda:revenue==null||variable==null||fixed==null||stock_kg>tolerance?null:revenue-variable-fixed,cost_items};}
const unchanged=(a,b)=>Math.abs(a-b)<=Math.max(tolerance,1e-12*Math.max(Math.abs(a),Math.abs(b)));
function variance(q0,q1,r0,r1){if(unchanged(q0,q1)&&r0===r1)return 0;const v0=Math.abs(q0)<=tolerance?0:r0==null?null:q0*r0,v1=Math.abs(q1)<=tolerance?0:r1==null?null:q1*r1;return diff(v1,v0);}
const sumVariances=values=>values.some(v=>v==null)?null:values.reduce((a,v)=>a+v,0);
function revenueVariance(d,b,t,targetPrices=false){return sumVariances(d.products.map(p=>variance(b.product_quantities[p.code],t.product_quantities[p.code],p.kind==='sale'?p.baseline_price:0,p.kind==='sale'?(targetPrices&&p.target_price!=null?p.target_price:p.baseline_price):0)));}
function driver(s,name){return name.startsWith('route:')?s.route_quantities[name.slice(6)]:name.startsWith('product:')?s.product_quantities[name.slice(8)]:s[name];}
function physicalUnchanged(b,t){return ['eggs_set','placed_chicks','live_heads','live_kg','feed_kg','meat_kg','sold_kg','loss_kg','stock_kg'].every(k=>unchanged(b[k],t[k]))&&['route_quantities','product_quantities'].every(key=>Object.entries(b[key]).every(([k,v])=>unchanged(v,t[key][k])));}
function expenseVariance(d,b,t){const items=d.costs.map(c=>({code:c.code,driver:c.driver,baseline_quantity:driver(b,c.driver),target_quantity:driver(t,c.driver),baseline_rate:c.baseline_rate,target_rate:c.target_rate??c.baseline_rate,expense_delta:c.baseline_rate==null&&(c.target_rate??c.baseline_rate)==null&&Math.abs(driver(b,c.driver))>tolerance&&!d.incremental_assumptions.unknown_rates_unchanged?null:variance(driver(b,c.driver),driver(t,c.driver),c.baseline_rate,c.target_rate??c.baseline_rate)}));const value=!d.costs_complete&&(!physicalUnchanged(b,t)||!d.incremental_assumptions.unlisted_expenses_unchanged)?null:sumVariances(items.map(i=>i.expense_delta));return {rub:value==null?null:-value,items};}
const samePeriod=(a,b)=>{const norm=v=>v.replace(/\s+/g,'').replace(/[—-]/g,'–').toLocaleLowerCase('ru');return norm(a)===norm(b);};
export function productionCase(input){const d={costs:[],capacities:[],baseline_fixed_expenses:null,target_fixed_expenses:null,costs_complete:false,expenses_confirmed:false,demand_confirmed:false,capacity_scope_confirmed:false,price_basis:'После исключения НДС и скидок',currency:'руб',sources:{},incremental_assumptions:{},additional_depreciation:null,depreciation_confirmed:false,depreciation_source:null,depreciation_period:null,...structuredClone(input)};for(const key of ['depreciation_source','depreciation_period'])if(typeof d[key]==='string'&&!d[key].trim())d[key]=null;d.changes={eggs_pct:0,hatch_pp:0,chick_reject_pp:0,mortality_pp:0,average_weight_pct:0,fcr_pct:0,slaughter_yield_pp:0,...d.changes};d.routes=d.routes.map(r=>({added_mass_per_kg:0,target_added_mass_per_kg:null,confirmed:false,...r}));d.products=d.products.map(p=>({target_price:null,target_route_yields:null,additional_demand_kg:null,confirmed:false,...p}));d.costs=d.costs.map(c=>({target_rate:null,confirmed:false,...c}));d.capacities=d.capacities.map(c=>({capacity_basis:'monthly_flow',baseline_peak_stock:null,target_peak_stock:null,confirmed:false,...c}));validate(d);
 const b=d.baseline,zero=Object.fromEntries(Object.keys(d.changes).map(k=>[k,0])),baseState=productionState(b,zero),targetState=productionState(b,d.changes);const baseline=basket(d,baseState,false),afterYield=basket(d,targetState,false),afterMix=basket({...d,products:d.products.map(p=>({...p,target_price:p.baseline_price}))},targetState,true),target=basket(d,targetState,true);
 const expense=expenseVariance(d,baseline,target),fixedVariance=d.baseline_fixed_expenses==null&&d.target_fixed_expenses==null?(d.incremental_assumptions.unknown_fixed_expenses_unchanged?0:null):diff(baseline.fixed_expenses,target.fixed_expenses);
 const bridge=[['yield','Изменение выхода',revenueVariance(d,baseline,afterYield)],['mix','Изменение структуры продукции',revenueVariance(d,afterYield,afterMix)],['price','Изменение цены',revenueVariance(d,afterMix,target,true)],['variable_cost','Изменение переменных расходов',expense.rub],['fixed_cost','Изменение постоянных расходов',fixedVariance]].map(([code,name,rub])=>({code,name,rub}));
 const demand=d.products.filter(p=>p.kind==='sale').map(p=>{const additional=Math.max(0,target.product_quantities[p.code]-baseline.product_quantities[p.code]),excess=p.additional_demand_kg==null&&additional>tolerance?null:Math.max(0,additional-(p.additional_demand_kg||0));return {code:p.code,name:p.name,additional_kg:additional,demand_kg:p.additional_demand_kg,excess_kg:excess,status:d.demand_confirmed&&excess!=null&&excess<=tolerance?'Подтверждено':'На согласовании'};});
 const capacities=d.capacities.map(c=>{const targetCap=c.target_capacity_per_month??c.capacity_per_month,limit=c.capacity_per_month==null?null:c.capacity_per_month*(c.capacity_basis==='peak_stock'?1:b.months),targetLimit=targetCap==null?null:targetCap*(c.capacity_basis==='peak_stock'?1:b.months),baseLoad=c.capacity_basis==='peak_stock'?c.baseline_peak_stock:c.baseline_flow_per_meat_kg==null?null:baseline.meat_kg*c.baseline_flow_per_meat_kg,targetLoad=c.capacity_basis==='peak_stock'?c.target_peak_stock:c.target_flow_per_meat_kg==null?null:target.meat_kg*c.target_flow_per_meat_kg;return {code:c.code,name:c.name,unit:c.unit,capacity:limit,target_capacity:targetLimit,baseline_load:baseLoad,target_load:targetLoad,target_loading:!targetLimit||targetLoad==null?null:targetLoad/targetLimit,status:limit!=null&&targetLimit!=null&&baseLoad!=null&&targetLoad!=null&&baseLoad<=limit+tolerance&&targetLoad<=targetLimit+tolerance&&c.confirmed?'Подтверждено':'На согласовании'};});
 const absoluteDelta=diff(target.ebitda,baseline.ebitda);if(absoluteDelta==null&&bridge[2].rub!=null&&bridge[2].rub!==0&&!d.incremental_assumptions.price_linked_expenses_unchanged)bridge[3].rub=null;const bridgeSum=sumVariances(bridge.map(r=>r.rub)),stockReady=baseline.stock_kg<=tolerance&&target.stock_kg<=tolerance,delta=absoluteDelta??(stockReady?bridgeSum:null),estimateBasis=absoluteDelta!=null?'absolute_states':delta!=null?'driver_variance':'requires_inputs',checks={'Производственная база':b.confirmed,'Матрица конечных выходов':d.routes.every(r=>r.confirmed)&&d.products.every(p=>p.confirmed),'Цены конечных продуктов':d.products.every(p=>p.kind!=='sale'||(p.baseline_price!=null&&(p.target_price??p.baseline_price)!=null)||(Math.abs(baseline.product_quantities[p.code])<=tolerance&&Math.abs(target.product_quantities[p.code])<=tolerance)),'Состав и ставки расходов':d.costs_complete&&d.expenses_confirmed&&d.costs.every(c=>c.confirmed&&((c.baseline_rate!=null&&(c.target_rate??c.baseline_rate)!=null)||(Math.abs(driver(baseline,c.driver))<=tolerance&&Math.abs(driver(target,c.driver))<=tolerance))),'Постоянные расходы':d.expenses_confirmed&&d.baseline_fixed_expenses!=null&&d.target_fixed_expenses!=null,'Спрос конечных продуктов':d.demand_confirmed&&demand.every(x=>x.status==='Подтверждено'),'Мощности маршрутов':d.capacity_scope_confirmed&&capacities.length>0&&capacities.every(x=>x.status==='Подтверждено'),'Календарь запасов':baseline.stock_kg<=tolerance&&target.stock_kg<=tolerance,'Денежный расчёт':delta!=null};const gaps=Object.keys(checks).filter(k=>!checks[k]),approved=gaps.length?null:delta;
 const depreciationPeriod=d.depreciation_period||b.period,periodComparable=samePeriod(depreciationPeriod,b.period),deltaEbit=delta==null||d.additional_depreciation==null||!periodComparable?null:delta-d.additional_depreciation;const ebitChecks={'Оценка EBITDA':delta!=null,'Дополнительная амортизация':d.additional_depreciation!=null,'Сопоставимый период амортизации':periodComparable,'Финансовое согласование EBITDA':approved!=null,'Финансовое согласование амортизации':d.depreciation_confirmed&&!!d.depreciation_source?.trim()},ebitGaps=Object.keys(ebitChecks).filter(k=>!ebitChecks[k]),approvedEbit=ebitGaps.length?null:deltaEbit;
 return {baseline_period:b.period,months:b.months,unit:'руб за исходный период',annual_unit:'руб за год выбранного режима',price_basis:d.price_basis,sources:{production:b.source,...d.sources},baseline,target,bridge,bridge_sum:bridgeSum,bridge_residual:diff(delta,bridgeSum),revenue_delta:diff(target.revenue,baseline.revenue),period_delta_ebitda:delta,estimate_status:delta!=null?"Оценка рассчитана":"Требуется расчёт",incremental_assumptions:d.incremental_assumptions,estimate_basis:estimateBasis,absolute_ebitda_complete:absoluteDelta!=null,expense_variance_items:expense.items,additional_depreciation:d.additional_depreciation,depreciation_period:depreciationPeriod,depreciation_period_comparable:periodComparable,period_delta_ebit:deltaEbit,annual_run_rate_delta_ebit:deltaEbit==null?null:deltaEbit*12/b.months,approved_delta_ebit:approvedEbit,approved_annual_run_rate_delta_ebit:approvedEbit==null?null:approvedEbit*12/b.months,ebit_status:approvedEbit!=null?"Подтверждено":deltaEbit!=null?"Оценка рассчитана":"Требуется расчёт EBIT",ebit_confirmation_fields:ebitGaps,annual_run_rate_delta:delta==null?null:delta*12/b.months,approved_delta_ebitda:approved,approved_annual_run_rate_delta:approved==null?null:approved*12/b.months,status:gaps.length?'На согласовании':'Подтверждено',confirmation_fields:gaps,demand,capacities,reconciliation:{placement_timing_factor:b.placed_chicks/(b.eggs_set*b.hatch_rate*(1-b.chick_reject_rate)),mortality_timing_factor:b.live_heads/(b.placed_chicks*(1-b.mortality_rate)),feed_timing_factor:(b.feed_kg??b.live_kg*b.fcr)/(b.live_kg*b.fcr),feed_basis:b.feed_kg!=null?'Наблюдаемый расход':'Расчётная потребность по конверсии корма',method:'Наблюдаемая база × относительное изменение операционных факторов'}};
}
export function commonPriceChange(input){if(!input)return null;const rows=(input.products||[]).filter(p=>p.kind==='sale'&&typeof p.baseline_price==='number'&&p.baseline_price>0);if(!rows.length)return null;const ratios=rows.map(p=>(p.target_price??p.baseline_price)/p.baseline_price-1);return ratios.every(v=>Math.abs(v-ratios[0])<1e-8)?ratios[0]*100:null;}
